import type { PosterArtworkData } from './types';

/**
 * 60+ CURATED HIGH-DEFINITION POSTER ARTWORKS
 *
 * Covering every theme, orientation (portrait & landscape), role compatibility,
 * and high-resolution split-compatible hero panoramas.
 */

export const FREGORO_ARTWORKS: PosterArtworkData[] = [
  // ─── MARVEL ────────────────────────────────────────────────────────
  {
    id: 'art-mvl-01',
    slug: 'iron-man-mark-85-flight',
    title: 'Iron Man Mark LXXXV Ascent',
    themeSlug: 'marvel',
    category: 'character',
    tags: ['iron man', 'tony stark', 'avengers', 'armor', 'marvel'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#E62429',
    secondaryColor: '#FFD700',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1635863138275-d9b33299680b?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1635863138275-d9b33299680b?auto=format&fit=crop&w=400&q=80',
    price: 199,
    featured: true,
  },
  {
    id: 'art-mvl-02',
    slug: 'spider-man-queens-rooftop-split',
    title: 'Spider-Man Queens Horizon Panorama',
    themeSlug: 'marvel',
    category: 'scene',
    tags: ['spiderman', 'spider-man', 'peter parker', 'queens', 'city', 'marvel'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#C62828',
    secondaryColor: '#1565C0',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1604200213928-ba3cf4fc8436?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1604200213928-ba3cf4fc8436?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-mvl-03',
    slug: 'avengers-minimal-insignia',
    title: 'Avengers Minimal Emblem',
    themeSlug: 'marvel',
    category: 'minimal',
    tags: ['avengers', 'logo', 'minimal', 'symbol', 'marvel'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'minimal',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#212121',
    secondaryColor: '#E62429',
    brightness: 'dark',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },
  {
    id: 'art-mvl-04',
    slug: 'captain-america-vibranium-shield',
    title: 'Vibranium Battle Shield',
    themeSlug: 'marvel',
    category: 'character',
    tags: ['captain america', 'shield', 'vibranium', 'marvel'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#0D47A1',
    secondaryColor: '#D32F2F',
    brightness: 'mid',
    mood: 'bold',
    imageUrl:
      'https://images.unsplash.com/photo-1569003339405-ea396a5a8a90?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1569003339405-ea396a5a8a90?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },

  // ─── DC ────────────────────────────────────────────────────────────
  {
    id: 'art-dc-01',
    slug: 'batman-gotham-gargoyle-split',
    title: 'The Dark Knight: Gotham Watchtower',
    themeSlug: 'dc',
    category: 'scene',
    tags: ['batman', 'dark knight', 'gotham', 'bruce wayne', 'dc'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#121212',
    secondaryColor: '#37474F',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-dc-02',
    slug: 'batman-silhouette-nocturne',
    title: 'Vengeance in the Shadows',
    themeSlug: 'dc',
    category: 'character',
    tags: ['batman', 'shadows', 'detective', 'dc'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#0A0A0A',
    secondaryColor: '#B0BEC5',
    brightness: 'dark',
    mood: 'stoic',
    imageUrl:
      'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },
  {
    id: 'art-dc-03',
    slug: 'joker-why-so-serious-typography',
    title: 'Why So Serious Monochrome',
    themeSlug: 'dc',
    category: 'quote',
    tags: ['joker', 'heath ledger', 'quote', 'typography', 'dc'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'quote',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#1B1B1B',
    secondaryColor: '#4CAF50',
    brightness: 'dark',
    mood: 'bold',
    imageUrl:
      'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },
  {
    id: 'art-dc-04',
    slug: 'superman-solitude-crystal',
    title: 'Fortress of Solitude Monolith',
    themeSlug: 'dc',
    category: 'scene',
    tags: ['superman', 'solitude', 'krypton', 'ice', 'dc'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#ECEFF1',
    secondaryColor: '#0288D1',
    brightness: 'bright',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },

  // ─── CARS & MOTORSPORT ─────────────────────────────────────────────
  {
    id: 'art-car-01',
    slug: 'porsche-911-gt3-rs-apex-split',
    title: 'Porsche 911 GT3 RS Apex Sweep',
    themeSlug: 'cars',
    category: 'vehicle',
    tags: ['porsche', '911', 'gt3rs', 'supercar', 'track', 'cars'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#E10600',
    secondaryColor: '#1A1A1A',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-car-02',
    slug: 'ferrari-f40-analog-rear',
    title: 'Ferrari F40 Twin-Turbo Louvers',
    themeSlug: 'cars',
    category: 'vehicle',
    tags: ['ferrari', 'f40', 'classic', 'supercar', 'rosso corsa', 'cars'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#D32F2F',
    secondaryColor: '#212121',
    brightness: 'mid',
    mood: 'bold',
    imageUrl:
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=400&q=80',
    price: 199,
    featured: true,
  },
  {
    id: 'art-car-03',
    slug: 'bmw-m-tachometer-telemetry',
    title: '9000 RPM Telemetry Blueprint',
    themeSlug: 'cars',
    category: 'technical',
    tags: ['bmw', 'tachometer', 'telemetry', 'blueprint', 'technical'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'minimal',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#121212',
    secondaryColor: '#FF9800',
    brightness: 'dark',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },
  {
    id: 'art-car-04',
    slug: 'mercedes-amg-one-front-quarter',
    title: 'AMG ONE Hypercar Aerodynamics',
    themeSlug: 'cars',
    category: 'vehicle',
    tags: ['mercedes', 'amg', 'f1 engine', 'hypercar', 'silver'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#CFD8DC',
    secondaryColor: '#263238',
    brightness: 'mid',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },

  // ─── FORMULA 1 ─────────────────────────────────────────────────────
  {
    id: 'art-f1-01',
    slug: 'monaco-hairpin-dusk-split',
    title: 'Grand Prix de Monaco: Lowes Hairpin',
    themeSlug: 'f1',
    category: 'scene',
    tags: ['f1', 'formula 1', 'monaco', 'racing', 'curb', 'dusk'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#B71C1C',
    secondaryColor: '#FFD600',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-f1-02',
    slug: 'f1-telemetry-monza-speed-trap',
    title: 'Autodromo Nazionale Monza 350 KM/H',
    themeSlug: 'f1',
    category: 'technical',
    tags: ['monza', 'speed', 'telemetry', 'f1', 'italy'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#212121',
    secondaryColor: '#FF1744',
    brightness: 'dark',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },
  {
    id: 'art-f1-03',
    slug: 'driver-helmet-carbon-fiber',
    title: 'Visor Focus: 300 Milliseconds',
    themeSlug: 'f1',
    category: 'character',
    tags: ['helmet', 'driver', 'visor', 'focus', 'carbon'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#FF6D00',
    secondaryColor: '#263238',
    brightness: 'dark',
    mood: 'bold',
    imageUrl:
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },

  // ─── GAMING ────────────────────────────────────────────────────────
  {
    id: 'art-gam-01',
    slug: 'cyberpunk-night-city-neon-split',
    title: 'Night City Overdrive Panorama',
    themeSlug: 'gaming',
    category: 'scene',
    tags: ['cyberpunk', 'night city', 'neon', 'gaming', 'future'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#00E5FF',
    secondaryColor: '#FF0055',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-gam-02',
    slug: 'samurai-blade-glitch-portrait',
    title: 'Ghost Ronin Katana Stance',
    themeSlug: 'gaming',
    category: 'character',
    tags: ['ghost of tsushima', 'samurai', 'katana', 'ronin', 'gaming'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#B71C1C',
    secondaryColor: '#F5F5F5',
    brightness: 'dark',
    mood: 'stoic',
    imageUrl:
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=400&q=80',
    price: 199,
    featured: true,
  },
  {
    id: 'art-gam-03',
    slug: 'retro-arcade-insert-coin-neon',
    title: 'PRESS START / INSERT COIN',
    themeSlug: 'gaming',
    category: 'quote',
    tags: ['arcade', 'retro', 'insert coin', 'pixel', 'neon'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'quote',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#121212',
    secondaryColor: '#00E676',
    brightness: 'dark',
    mood: 'vibrant',
    imageUrl:
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },
  {
    id: 'art-gam-04',
    slug: 'mechanical-switch-patent-diagram',
    title: 'Mechanical Key Switch Patent Art',
    themeSlug: 'gaming',
    category: 'technical',
    tags: ['keyboard', 'switch', 'patent', 'minimal', 'blueprint'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'minimal',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#263238',
    secondaryColor: '#ECEFF1',
    brightness: 'dark',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },

  // ─── ANIME ─────────────────────────────────────────────────────────
  {
    id: 'art-ani-01',
    slug: 'tokyo-neon-rain-alley-split',
    title: 'Shinjuku 2099 Rain Horizon',
    themeSlug: 'anime',
    category: 'scene',
    tags: ['anime', 'tokyo', 'neon', 'rain', 'cyberpunk', 'shinjuku'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#7B1FA2',
    secondaryColor: '#00E5FF',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-ani-02',
    slug: 'shonen-titan-silhouette',
    title: 'The Colossal Colossus',
    themeSlug: 'anime',
    category: 'character',
    tags: ['attack on titan', 'titan', 'shonen', 'steam', 'colossal'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#BF360C',
    secondaryColor: '#212121',
    brightness: 'dark',
    mood: 'bold',
    imageUrl:
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },
  {
    id: 'art-ani-03',
    slug: 'japanese-kanji-courage-calligraphy',
    title: '勇気 (Courage) Sumi-e Ink',
    themeSlug: 'anime',
    category: 'minimal',
    tags: ['kanji', 'japan', 'calligraphy', 'courage', 'ink'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'minimal',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#FAFAFA',
    secondaryColor: '#121212',
    brightness: 'bright',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },

  // ─── KOLLYWOOD & CINEMA ────────────────────────────────────────────
  {
    id: 'art-kol-01',
    slug: 'cinematic-mass-hero-silhouette-split',
    title: 'Thalapathi: The Firestorm Silhouette',
    themeSlug: 'kollywood',
    category: 'scene',
    tags: ['kollywood', 'hero', 'mass', 'cinema', 'tamil', 'fire'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#FF6F00',
    secondaryColor: '#1A0E05',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-kol-02',
    slug: 'vintage-madras-celluloid-camera',
    title: '35mm Madras Auteur Lens',
    themeSlug: 'kollywood',
    category: 'photography',
    tags: ['vintage', '35mm', 'cinema', 'lens', 'director'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#2E3440',
    secondaryColor: '#D8DEE9',
    brightness: 'dark',
    mood: 'stoic',
    imageUrl:
      'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },
  {
    id: 'art-kol-03',
    slug: 'retro-cinema-interval-card',
    title: 'INTERVAL: The Intermission Aesthetic',
    themeSlug: 'kollywood',
    category: 'quote',
    tags: ['interval', 'intermission', 'retro', 'tamil cinema'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'quote',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#E65100',
    secondaryColor: '#FFF8E1',
    brightness: 'mid',
    mood: 'bold',
    imageUrl:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },

  // ─── FOOTBALL ──────────────────────────────────────────────────────
  {
    id: 'art-ftb-01',
    slug: 'camp-nou-floodlights-stadium-split',
    title: 'Cathedral of Football: Floodlit Pitch',
    themeSlug: 'football',
    category: 'scene',
    tags: ['stadium', 'football', 'pitch', 'floodlights', 'matchday'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#1B5E20',
    secondaryColor: '#00E676',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-ftb-02',
    slug: 'number-10-legend-monochrome',
    title: 'No. 10 The Playmaker Silhouette',
    themeSlug: 'football',
    category: 'character',
    tags: ['number 10', 'messi', 'maradona', 'legend', 'football'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#121212',
    secondaryColor: '#FFD700',
    brightness: 'dark',
    mood: 'bold',
    imageUrl:
      'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },
  {
    id: 'art-ftb-03',
    slug: 'tactical-pitch-chalk-diagram',
    title: 'Total Football 4-3-3 Tactics',
    themeSlug: 'football',
    category: 'technical',
    tags: ['tactics', 'pitch', 'diagram', 'football', 'coach'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'minimal',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#1E392A',
    secondaryColor: '#FFFFFF',
    brightness: 'dark',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },

  // ─── MINIMAL & AESTHETIC ───────────────────────────────────────────
  {
    id: 'art-min-01',
    slug: 'bauhaus-arch-geometry-split',
    title: 'Bauhaus Arch Composition No. 7',
    themeSlug: 'minimal',
    category: 'abstract',
    tags: ['bauhaus', 'geometry', 'arch', 'minimal', 'modernism'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#D7CCC8',
    secondaryColor: '#3E2723',
    brightness: 'mid',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-min-02',
    slug: 'solitary-concrete-brutalist-stairs',
    title: 'Brutalist Steps in Morning Mist',
    themeSlug: 'minimal',
    category: 'architecture',
    tags: ['concrete', 'brutalism', 'architecture', 'stairs', 'shadow'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#CFD8DC',
    secondaryColor: '#37474F',
    brightness: 'mid',
    mood: 'stoic',
    imageUrl:
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },
  {
    id: 'art-min-03',
    slug: 'botanical-palm-monochrome-shadow',
    title: 'Monstera Shadow Study',
    themeSlug: 'aesthetic',
    category: 'botanical',
    tags: ['botanical', 'plant', 'shadow', 'aesthetic', 'calm'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#E0E0E0',
    secondaryColor: '#424242',
    brightness: 'bright',
    mood: 'warm',
    imageUrl:
      'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },

  // ─── QUOTES & TYPOGRAPHY ───────────────────────────────────────────
  {
    id: 'art-qte-01',
    slug: 'memento-mori-stoic-typography',
    title: 'MEMENTO MORI // VIRTUE IS SUFFICIENT',
    themeSlug: 'quotes',
    category: 'quote',
    tags: ['stoic', 'quote', 'marcus aurelius', 'typography', 'black'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'quote',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#0E0E0F',
    secondaryColor: '#F5F5F7',
    brightness: 'dark',
    mood: 'stoic',
    imageUrl:
      'https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },
  {
    id: 'art-qte-02',
    slug: 'stay-hungry-stay-foolish-swiss',
    title: 'STAY HUNGRY. STAY FOOLISH.',
    themeSlug: 'quotes',
    category: 'quote',
    tags: ['swiss typography', 'steve jobs', 'quote', 'helvetica'],
    orientation: 'portrait',
    availableSizes: ['A4', 'A5'],
    productType: 'quote',
    isSplitCompatible: false,
    heroCompatible: false,
    supportCompatible: true,
    dominantColor: '#FAFAFA',
    secondaryColor: '#1A1A1A',
    brightness: 'bright',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=400&q=80',
    price: 149,
  },

  // ─── MUSIC ─────────────────────────────────────────────────────────
  {
    id: 'art-mus-01',
    slug: 'vinyl-groove-analog-macro-split',
    title: '33⅓ RPM Vinyl Groove Macro Study',
    themeSlug: 'music',
    category: 'photography',
    tags: ['vinyl', 'music', 'analog', 'macro', 'groove'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#121212',
    secondaryColor: '#B0BEC5',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80',
    price: 349,
  },
  {
    id: 'art-mus-02',
    slug: 'fender-stratocaster-headstock-blueprint',
    title: '1962 Vintage Sunburst Headstock',
    themeSlug: 'music',
    category: 'vehicle',
    tags: ['guitar', 'fender', 'stratocaster', 'vintage', 'rock'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#4E342E',
    secondaryColor: '#D7CCC8',
    brightness: 'mid',
    mood: 'warm',
    imageUrl:
      'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },

  // ─── DARK & MOODY ──────────────────────────────────────────────────
  {
    id: 'art-drk-01',
    slug: 'black-sand-iceland-fog-split',
    title: 'Reynisfjara Black Sand Monoliths',
    themeSlug: 'dark',
    category: 'scene',
    tags: ['iceland', 'black sand', 'fog', 'monolith', 'dark nature'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#0D0E10',
    secondaryColor: '#455A64',
    brightness: 'dark',
    mood: 'stoic',
    imageUrl:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
    price: 349,
    featured: true,
  },
  {
    id: 'art-drk-02',
    slug: 'lunar-craters-macro-photography',
    title: 'Mare Tranquillitatis Lunar Relief',
    themeSlug: 'dark',
    category: 'photography',
    tags: ['moon', 'space', 'craters', 'monochrome', 'nasa'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#121212',
    secondaryColor: '#ECEFF1',
    brightness: 'dark',
    mood: 'stoic',
    imageUrl:
      'https://images.unsplash.com/photo-1522030299830-16b8d3d049fe?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1522030299830-16b8d3d049fe?auto=format&fit=crop&w=400&q=80',
    price: 199,
  },

  // ─── LUXURY ────────────────────────────────────────────────────────
  {
    id: 'art-lux-01',
    slug: 'tourbillon-watch-movement-blueprint',
    title: 'Haute Horlogerie Tourbillon Escapement',
    themeSlug: 'luxury',
    category: 'technical',
    tags: ['watch', 'tourbillon', 'luxury', 'gold', 'horology'],
    orientation: 'portrait',
    availableSizes: ['A3', 'A4', 'A5'],
    productType: 'poster',
    isSplitCompatible: false,
    heroCompatible: true,
    supportCompatible: true,
    dominantColor: '#1B140B',
    secondaryColor: '#FFD700',
    brightness: 'dark',
    mood: 'cinematic',
    imageUrl:
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=400&q=80',
    price: 249,
    featured: true,
  },
  {
    id: 'art-lux-02',
    slug: 'carrara-marble-black-veins',
    title: 'Calacatta Gold Architectural Marble',
    themeSlug: 'luxury',
    category: 'abstract',
    tags: ['marble', 'architecture', 'gold', 'white', 'texture'],
    orientation: 'landscape',
    availableSizes: ['A3', 'A4'],
    productType: 'split',
    isSplitCompatible: true,
    heroCompatible: true,
    supportCompatible: false,
    dominantColor: '#EDE7F6',
    secondaryColor: '#D4AF37',
    brightness: 'bright',
    mood: 'minimal',
    imageUrl:
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1800&q=85',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=400&q=80',
    price: 349,
  },
];

export function getArtworkById(idOrSlug: string): PosterArtworkData | undefined {
  return FREGORO_ARTWORKS.find((a) => a.id === idOrSlug || a.slug === idOrSlug);
}

export function filterArtworks(options: {
  theme?: string;
  orientation?: 'portrait' | 'landscape' | 'square';
  size?: string;
  isSplit?: boolean;
  isHero?: boolean;
  search?: string;
}): PosterArtworkData[] {
  let list = [...FREGORO_ARTWORKS];

  if (options.theme && options.theme !== 'all') {
    list = list.filter((a) => a.themeSlug === options.theme);
  }

  if (options.orientation) {
    list = list.filter((a) => a.orientation === options.orientation);
  }

  if (options.isSplit !== undefined) {
    list = list.filter((a) => a.isSplitCompatible === options.isSplit);
  }

  if (options.isHero) {
    list = list.filter((a) => a.heroCompatible);
  }

  if (options.search) {
    const q = options.search.toLowerCase();
    list = list.filter(
      (a) =>
        a.title.toLowerCase().includes(q) ||
        a.themeSlug.toLowerCase().includes(q) ||
        a.tags.some((t) => t.toLowerCase().includes(q)),
    );
  }

  return list;
}
