import type { WallLayoutData } from './types';

/**
 * ARCHITECTURALLY ENGINEERED FREGORO SIGNATURE LAYOUTS
 *
 * Distinct categories:
 * 1. HYBRID COMBOS: Central continuous split poster framed by surrounding individual posters (Horizontal flanks, vertical rows, or full surround).
 * 2. MULTI-PANEL SPLIT ART: Pure, uninterrupted continuous split artworks.
 * 3. CURATED GALLERY WALLS: Collections of distinct artworks with balanced museum negative space.
 */

export const FREGORO_LAYOUTS: WallLayoutData[] = [
  {
    id: 'hybrid-stepped-triptych-flank-5',
    slug: 'hybrid-stepped-triptych-flank',
    name: 'Stepped Triptych Dual-Pillar',
    category: 'hybrid',
    description:
      'Iconic 3-panel stepped split poster (6×9", 6×11", 6×9") flanked by dual vertical A4 museum pillars.',
    badge: 'Stepped Split Combo',
    wallWidthMm: 1052,
    wallHeightMm: 417,
    coverageLabel: '93 × 30 cm',
    physicalPrintCount: 5,
    logicalArtworkCount: 3,
    recommendedRoom: 'Study / Bedroom / Office Gallery',
    recommendedWallWidth: '1.4 – 1.8 m',
    recommendedThemes: ['DC', 'Marvel', 'Anime', 'Gaming', 'Cars'],
    basePrice: 1699,
    compareAtPrice: 2299,
    slots: [
      {
        id: 'slot-stf5-left-a4',
        slotType: 'accent',
        x: 0.057,
        y: 0.1439,
        width: 0.1996,
        height: 0.7122,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Pillar (A4)',
      },
      {
        id: 'slot-stf5-split-1',
        slotType: 'hero-panel',
        x: 0.2709,
        y: 0.2254,
        width: 0.1445,
        height: 0.5492,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Left 6×9" (152×229mm)',
        splitGroupId: 'split-stf5-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-stf5-split-2',
        slotType: 'hero-panel',
        x: 0.4278,
        y: 0.1655,
        width: 0.1445,
        height: 0.6691,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 279,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Center 6×11" (152×279mm)',
        splitGroupId: 'split-stf5-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-stf5-split-3',
        slotType: 'hero-panel',
        x: 0.5846,
        y: 0.2254,
        width: 0.1445,
        height: 0.5492,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Right 6×9" (152×229mm)',
        splitGroupId: 'split-stf5-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-stf5-right-a4',
        slotType: 'accent',
        x: 0.7433,
        y: 0.1439,
        width: 0.1996,
        height: 0.7122,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Pillar (A4)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-stf5-hero',
        name: 'Stepped 3-Piece Split Artwork',
        panelCount: 3,
        orientation: 'portrait',
        physicalSize: 'CUSTOM',
        slotIds: ['slot-stf5-split-1', 'slot-stf5-split-2', 'slot-stf5-split-3'],
        staggered: true,
      },
    ],
    version: 1,
    sortOrder: 1,
    published: true,
  },
  {
    id: 'hybrid-stepped-triptych-crown-7',
    slug: 'hybrid-stepped-triptych-crown',
    name: 'Stepped Triptych 13×19 Crown Showcase',
    category: 'hybrid',
    description:
      'Continuous 3-panel stepped split crowned by an expansive 13×19" panorama header and framed with A4 prints.',
    badge: 'Crown Showcase',
    wallWidthMm: 1052,
    wallHeightMm: 987,
    coverageLabel: '93 × 87 cm',
    physicalPrintCount: 7,
    logicalArtworkCount: 5,
    recommendedRoom: 'Living Room Feature Wall / Entertainment Area',
    recommendedWallWidth: '1.8 – 2.4 m',
    recommendedThemes: ['Cars', 'Marvel', 'DC', 'Cinematic', 'Gaming'],
    basePrice: 2499,
    compareAtPrice: 3399,
    slots: [
      {
        id: 'slot-stc7-crown',
        slotType: 'hero',
        x: 0.2704,
        y: 0.0608,
        width: 0.4591,
        height: 0.3343,
        size: '13x19',
        physicalWidthMm: 483,
        physicalHeightMm: 330,
        orientation: 'landscape',
        required: true,
        label: 'Panorama Header Crown (13×19")',
      },
      {
        id: 'slot-stc7-left-a4',
        slotType: 'accent',
        x: 0.057,
        y: 0.4103,
        width: 0.1996,
        height: 0.3009,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Flank (A4)',
      },
      {
        id: 'slot-stc7-split-1',
        slotType: 'hero-panel',
        x: 0.2709,
        y: 0.4448,
        width: 0.1445,
        height: 0.232,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Left 6×9" (152×229mm)',
        splitGroupId: 'split-stc7-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-stc7-split-2',
        slotType: 'hero-panel',
        x: 0.4278,
        y: 0.4195,
        width: 0.1445,
        height: 0.2827,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 279,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Center 6×11" (152×279mm)',
        splitGroupId: 'split-stc7-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-stc7-split-3',
        slotType: 'hero-panel',
        x: 0.5846,
        y: 0.4448,
        width: 0.1445,
        height: 0.232,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Right 6×9" (152×229mm)',
        splitGroupId: 'split-stc7-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-stc7-right-a4',
        slotType: 'accent',
        x: 0.7433,
        y: 0.4103,
        width: 0.1996,
        height: 0.3009,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Flank (A4)',
      },
      {
        id: 'slot-stc7-bot-a4',
        slotType: 'accent',
        x: 0.3588,
        y: 0.7264,
        width: 0.2823,
        height: 0.2128,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Lower Accent (A4)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-stc7-hero',
        name: 'Stepped 3-Piece Center Split',
        panelCount: 3,
        orientation: 'portrait',
        physicalSize: 'CUSTOM',
        slotIds: ['slot-stc7-split-1', 'slot-stc7-split-2', 'slot-stc7-split-3'],
        staggered: true,
      },
    ],
    version: 1,
    sortOrder: 2,
    published: true,
  },
  {
    id: 'hybrid-stepped-wave-flank-9',
    slug: 'hybrid-stepped-wave-flank',
    name: 'Apex 5-Panel Stepped Wave Flank',
    category: 'hybrid',
    description:
      'Signature 5-panel stepped wave split (reduced 50%) framed by dual stacked horizontal A5 gallery wings.',
    badge: 'Stepped 5-Panel Signature',
    wallWidthMm: 1132,
    wallHeightMm: 431,
    coverageLabel: '101 × 31 cm',
    physicalPrintCount: 9,
    logicalArtworkCount: 5,
    recommendedRoom: 'Living Room Feature Wall / Bedroom Headboard',
    recommendedWallWidth: '1.6 – 2.2 m',
    recommendedThemes: ['Anime', 'Marvel', 'DC', 'Gaming', 'Space'],
    basePrice: 2299,
    compareAtPrice: 3199,
    slots: [
      {
        id: 'slot-swf9-left-top',
        slotType: 'accent',
        x: 0.053,
        y: 0.1392,
        width: 0.1855,
        height: 0.3434,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Left Upper Wing (A5)',
      },
      {
        id: 'slot-swf9-left-bot',
        slotType: 'accent',
        x: 0.053,
        y: 0.5174,
        width: 0.1855,
        height: 0.3434,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Left Lower Wing (A5)',
      },
      {
        id: 'slot-swf9-split-1',
        slotType: 'hero-panel',
        x: 0.2518,
        y: 0.2784,
        width: 0.0901,
        height: 0.4432,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 191,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 1/5 (102×191mm)',
        splitGroupId: 'split-swf9-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-swf9-split-2',
        slotType: 'hero-panel',
        x: 0.3534,
        y: 0.2343,
        width: 0.0901,
        height: 0.5313,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 2/5 (102×229mm)',
        splitGroupId: 'split-swf9-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-swf9-split-3',
        slotType: 'hero-panel',
        x: 0.4549,
        y: 0.1903,
        width: 0.0901,
        height: 0.6195,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 267,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 3/5 Apex (102×267mm)',
        splitGroupId: 'split-swf9-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-swf9-split-4',
        slotType: 'hero-panel',
        x: 0.5565,
        y: 0.2343,
        width: 0.0901,
        height: 0.5313,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 4/5 (102×229mm)',
        splitGroupId: 'split-swf9-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-swf9-split-5',
        slotType: 'hero-panel',
        x: 0.6581,
        y: 0.2784,
        width: 0.0901,
        height: 0.4432,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 191,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 5/5 (102×191mm)',
        splitGroupId: 'split-swf9-hero',
        panelIndex: 4,
      },
      {
        id: 'slot-swf9-right-top',
        slotType: 'accent',
        x: 0.7615,
        y: 0.1392,
        width: 0.1855,
        height: 0.3434,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Right Upper Wing (A5)',
      },
      {
        id: 'slot-swf9-right-bot',
        slotType: 'accent',
        x: 0.7615,
        y: 0.5174,
        width: 0.1855,
        height: 0.3434,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Right Lower Wing (A5)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-swf9-hero',
        name: '5-Panel Stepped Wave Split',
        panelCount: 5,
        orientation: 'portrait',
        physicalSize: 'CUSTOM',
        slotIds: [
          'slot-swf9-split-1',
          'slot-swf9-split-2',
          'slot-swf9-split-3',
          'slot-swf9-split-4',
          'slot-swf9-split-5',
        ],
        staggered: true,
      },
    ],
    version: 1,
    sortOrder: 3,
    published: true,
  },
  {
    id: 'hybrid-stepped-wave-heritage-11',
    slug: 'hybrid-stepped-wave-heritage',
    name: 'Stepped Wave Grand 13×19 Heritage',
    category: 'hybrid',
    description:
      'Imperial 11-print showcase combining a 5-panel stepped wave with flagship 13×19" anchor pillars and A5 horizon frames.',
    badge: 'Flagship Heritage',
    wallWidthMm: 1372,
    wallHeightMm: 713,
    coverageLabel: '125 × 59 cm',
    physicalPrintCount: 11,
    logicalArtworkCount: 7,
    recommendedRoom: 'Grand Living Room / Executive Lounge',
    recommendedWallWidth: '2.0 – 2.6 m',
    recommendedThemes: ['Marvel', 'DC', 'Cars', 'Anime', 'Art'],
    basePrice: 3299,
    compareAtPrice: 4499,
    slots: [
      {
        id: 'slot-swh11-arch-left',
        slotType: 'hero',
        x: 0.0437,
        y: 0.1613,
        width: 0.2405,
        height: 0.6774,
        size: '13x19',
        physicalWidthMm: 330,
        physicalHeightMm: 483,
        orientation: 'portrait',
        required: true,
        label: 'Left Grand Anchor (13×19")',
      },
      {
        id: 'slot-swh11-top-1',
        slotType: 'accent',
        x: 0.3415,
        y: 0.0842,
        width: 0.1531,
        height: 0.2076,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Upper Center Left (A5)',
      },
      {
        id: 'slot-swh11-top-2',
        slotType: 'accent',
        x: 0.5055,
        y: 0.0842,
        width: 0.1531,
        height: 0.2076,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Upper Center Right (A5)',
      },
      {
        id: 'slot-swh11-split-1',
        slotType: 'hero-panel',
        x: 0.2952,
        y: 0.3661,
        width: 0.0743,
        height: 0.2679,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 191,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 1/5 (102×191mm)',
        splitGroupId: 'split-swh11-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-swh11-split-2',
        slotType: 'hero-panel',
        x: 0.379,
        y: 0.3394,
        width: 0.0743,
        height: 0.3212,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 2/5 (102×229mm)',
        splitGroupId: 'split-swh11-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-swh11-split-3',
        slotType: 'hero-panel',
        x: 0.4628,
        y: 0.3128,
        width: 0.0743,
        height: 0.3745,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 267,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 3/5 Apex (102×267mm)',
        splitGroupId: 'split-swh11-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-swh11-split-4',
        slotType: 'hero-panel',
        x: 0.5466,
        y: 0.3394,
        width: 0.0743,
        height: 0.3212,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 4/5 (102×229mm)',
        splitGroupId: 'split-swh11-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-swh11-split-5',
        slotType: 'hero-panel',
        x: 0.6305,
        y: 0.3661,
        width: 0.0743,
        height: 0.2679,
        size: 'CUSTOM',
        physicalWidthMm: 102,
        physicalHeightMm: 191,
        orientation: 'portrait',
        required: true,
        label: 'Wave Panel 5/5 (102×191mm)',
        splitGroupId: 'split-swh11-hero',
        panelIndex: 4,
      },
      {
        id: 'slot-swh11-bot-1',
        slotType: 'accent',
        x: 0.3415,
        y: 0.7083,
        width: 0.1531,
        height: 0.2076,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Lower Center Left (A5)',
      },
      {
        id: 'slot-swh11-bot-2',
        slotType: 'accent',
        x: 0.5055,
        y: 0.7083,
        width: 0.1531,
        height: 0.2076,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Lower Center Right (A5)',
      },
      {
        id: 'slot-swh11-arch-right',
        slotType: 'hero',
        x: 0.7157,
        y: 0.1613,
        width: 0.2405,
        height: 0.6774,
        size: '13x19',
        physicalWidthMm: 330,
        physicalHeightMm: 483,
        orientation: 'portrait',
        required: true,
        label: 'Right Grand Anchor (13×19")',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-swh11-hero',
        name: '5-Panel Stepped Wave Split',
        panelCount: 5,
        orientation: 'portrait',
        physicalSize: 'CUSTOM',
        slotIds: [
          'slot-swh11-split-1',
          'slot-swh11-split-2',
          'slot-swh11-split-3',
          'slot-swh11-split-4',
          'slot-swh11-split-5',
        ],
        staggered: true,
      },
    ],
    version: 1,
    sortOrder: 4,
    published: true,
  },
  {
    id: 'hybrid-grid2x2-heritage-6',
    slug: 'hybrid-grid2x2-heritage',
    name: 'Heritage 2×2 Salon with 13×19 Pillars',
    category: 'hybrid',
    description:
      'Harmonious 2×2 windowpane grid split of A5 panels flanked by dual statement 13×19" vertical posters.',
    badge: 'Curated Salon',
    wallWidthMm: 1121,
    wallHeightMm: 603,
    coverageLabel: '100 × 48 cm',
    physicalPrintCount: 6,
    logicalArtworkCount: 3,
    recommendedRoom: 'Studio / Office / Lounge Wall',
    recommendedWallWidth: '1.6 – 2.0 m',
    recommendedThemes: ['Minimalist', 'Anime', 'Marvel', 'Art', 'Cars'],
    basePrice: 2199,
    compareAtPrice: 2999,
    slots: [
      {
        id: 'slot-g2h6-arch-left',
        slotType: 'hero',
        x: 0.0535,
        y: 0.0995,
        width: 0.2944,
        height: 0.801,
        size: '13x19',
        physicalWidthMm: 330,
        physicalHeightMm: 483,
        orientation: 'portrait',
        required: true,
        label: 'Left Pillar (13×19")',
      },
      {
        id: 'slot-g2h6-split-1',
        slotType: 'hero-panel',
        x: 0.3613,
        y: 0.1393,
        width: 0.132,
        height: 0.3483,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 1/4 Top-Left (A5)',
        splitGroupId: 'split-g2h6-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-g2h6-split-2',
        slotType: 'hero-panel',
        x: 0.5067,
        y: 0.1393,
        width: 0.132,
        height: 0.3483,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 2/4 Top-Right (A5)',
        splitGroupId: 'split-g2h6-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-g2h6-split-3',
        slotType: 'hero-panel',
        x: 0.3613,
        y: 0.5124,
        width: 0.132,
        height: 0.3483,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 3/4 Bot-Left (A5)',
        splitGroupId: 'split-g2h6-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-g2h6-split-4',
        slotType: 'hero-panel',
        x: 0.5067,
        y: 0.5124,
        width: 0.132,
        height: 0.3483,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 4/4 Bot-Right (A5)',
        splitGroupId: 'split-g2h6-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-g2h6-arch-right',
        slotType: 'hero',
        x: 0.6521,
        y: 0.0995,
        width: 0.2944,
        height: 0.801,
        size: '13x19',
        physicalWidthMm: 330,
        physicalHeightMm: 483,
        orientation: 'portrait',
        required: true,
        label: 'Right Pillar (13×19")',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-g2h6-hero',
        name: '2×2 Continuous Grid Artwork',
        panelCount: 4,
        orientation: 'portrait',
        physicalSize: 'A5',
        slotIds: [
          'slot-g2h6-split-1',
          'slot-g2h6-split-2',
          'slot-g2h6-split-3',
          'slot-g2h6-split-4',
        ],
      },
    ],
    version: 1,
    sortOrder: 5,
    published: true,
  },
  {
    id: 'hybrid-grid3x2-panoramic-10',
    slug: 'hybrid-grid3x2-panoramic',
    name: 'Mosaic 3×2 Grid Gallery',
    category: 'hybrid',
    description:
      '6-piece continuous mosaic grid (A6 panels) framed symmetrically by 4 surrounding A4 standard prints.',
    badge: 'Mosaic Enclave',
    wallWidthMm: 909,
    wallHeightMm: 878,
    coverageLabel: '79 × 76 cm',
    physicalPrintCount: 10,
    logicalArtworkCount: 5,
    recommendedRoom: 'Creative Studio / Media Room',
    recommendedWallWidth: '1.6 – 2.2 m',
    recommendedThemes: ['Gaming', 'Anime', 'Marvel', 'Cinema'],
    basePrice: 2199,
    compareAtPrice: 2999,
    slots: [
      {
        id: 'slot-g32-top-a4',
        slotType: 'accent',
        x: 0.3366,
        y: 0.0683,
        width: 0.3267,
        height: 0.2392,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Header Banner (A4)',
      },
      {
        id: 'slot-g32-left-a4',
        slotType: 'accent',
        x: 0.066,
        y: 0.3309,
        width: 0.231,
        height: 0.3383,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Flank (A4)',
      },
      {
        id: 'slot-g32-split-1',
        slotType: 'hero-panel',
        x: 0.3135,
        y: 0.3246,
        width: 0.1155,
        height: 0.1686,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 1/6 (A6)',
        splitGroupId: 'split-g32-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-g32-split-2',
        slotType: 'hero-panel',
        x: 0.4422,
        y: 0.3246,
        width: 0.1155,
        height: 0.1686,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 2/6 (A6)',
        splitGroupId: 'split-g32-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-g32-split-3',
        slotType: 'hero-panel',
        x: 0.571,
        y: 0.3246,
        width: 0.1155,
        height: 0.1686,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 3/6 (A6)',
        splitGroupId: 'split-g32-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-g32-split-4',
        slotType: 'hero-panel',
        x: 0.3135,
        y: 0.5068,
        width: 0.1155,
        height: 0.1686,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 4/6 (A6)',
        splitGroupId: 'split-g32-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-g32-split-5',
        slotType: 'hero-panel',
        x: 0.4422,
        y: 0.5068,
        width: 0.1155,
        height: 0.1686,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 5/6 (A6)',
        splitGroupId: 'split-g32-hero',
        panelIndex: 4,
      },
      {
        id: 'slot-g32-split-6',
        slotType: 'hero-panel',
        x: 0.571,
        y: 0.5068,
        width: 0.1155,
        height: 0.1686,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 6/6 (A6)',
        splitGroupId: 'split-g32-hero',
        panelIndex: 5,
      },
      {
        id: 'slot-g32-right-a4',
        slotType: 'accent',
        x: 0.703,
        y: 0.3309,
        width: 0.231,
        height: 0.3383,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Flank (A4)',
      },
      {
        id: 'slot-g32-bot-a4',
        slotType: 'accent',
        x: 0.3366,
        y: 0.6925,
        width: 0.3267,
        height: 0.2392,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Footer Base (A4)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-g32-hero',
        name: '3×2 Continuous Mosaic Split',
        panelCount: 6,
        orientation: 'portrait',
        physicalSize: 'A6',
        slotIds: [
          'slot-g32-split-1',
          'slot-g32-split-2',
          'slot-g32-split-3',
          'slot-g32-split-4',
          'slot-g32-split-5',
          'slot-g32-split-6',
        ],
      },
    ],
    version: 1,
    sortOrder: 6,
    published: true,
  },
  {
    id: 'hybrid-grid3x3-matrix-11',
    slug: 'hybrid-grid3x3-matrix',
    name: 'Matrix 3×3 Core with 13×19 Guardians',
    category: 'hybrid',
    description:
      'Immersive 9-panel matrix grid split anchored on both wings by towering 13×19" vertical monoliths.',
    badge: 'High Impact Matrix',
    wallWidthMm: 1149,
    wallHeightMm: 603,
    coverageLabel: '103 × 48 cm',
    physicalPrintCount: 11,
    logicalArtworkCount: 3,
    recommendedRoom: 'Gamer Setup / Home Theater / Main Wall',
    recommendedWallWidth: '1.8 – 2.4 m',
    recommendedThemes: ['Cyberpunk', 'Marvel', 'DC', 'Gaming', 'Anime'],
    basePrice: 2899,
    compareAtPrice: 3899,
    slots: [
      {
        id: 'slot-g33-arch-left',
        slotType: 'hero',
        x: 0.0522,
        y: 0.0995,
        width: 0.2872,
        height: 0.801,
        size: '13x19',
        physicalWidthMm: 330,
        physicalHeightMm: 483,
        orientation: 'portrait',
        required: true,
        label: 'Left Guardian (13×19")',
      },
      {
        id: 'slot-g33-split-1',
        slotType: 'hero-panel',
        x: 0.3525,
        y: 0.1119,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 1/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-g33-split-2',
        slotType: 'hero-panel',
        x: 0.4543,
        y: 0.1119,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 2/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-g33-split-3',
        slotType: 'hero-panel',
        x: 0.5561,
        y: 0.1119,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 3/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-g33-split-4',
        slotType: 'hero-panel',
        x: 0.3525,
        y: 0.3773,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 4/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-g33-split-5',
        slotType: 'hero-panel',
        x: 0.4543,
        y: 0.3773,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 5/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 4,
      },
      {
        id: 'slot-g33-split-6',
        slotType: 'hero-panel',
        x: 0.5561,
        y: 0.3773,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 6/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 5,
      },
      {
        id: 'slot-g33-split-7',
        slotType: 'hero-panel',
        x: 0.3525,
        y: 0.6426,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 7/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 6,
      },
      {
        id: 'slot-g33-split-8',
        slotType: 'hero-panel',
        x: 0.4543,
        y: 0.6426,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 8/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 7,
      },
      {
        id: 'slot-g33-split-9',
        slotType: 'hero-panel',
        x: 0.5561,
        y: 0.6426,
        width: 0.0914,
        height: 0.2454,
        size: 'A6',
        physicalWidthMm: 105,
        physicalHeightMm: 148,
        orientation: 'portrait',
        required: true,
        label: 'Matrix Panel 9/9 (A6)',
        splitGroupId: 'split-g33-hero',
        panelIndex: 8,
      },
      {
        id: 'slot-g33-arch-right',
        slotType: 'hero',
        x: 0.6606,
        y: 0.0995,
        width: 0.2872,
        height: 0.801,
        size: '13x19',
        physicalWidthMm: 330,
        physicalHeightMm: 483,
        orientation: 'portrait',
        required: true,
        label: 'Right Guardian (13×19")',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-g33-hero',
        name: '3×3 Matrix Continuous Split',
        panelCount: 9,
        orientation: 'portrait',
        physicalSize: 'A6',
        slotIds: [
          'slot-g33-split-1',
          'slot-g33-split-2',
          'slot-g33-split-3',
          'slot-g33-split-4',
          'slot-g33-split-5',
          'slot-g33-split-6',
          'slot-g33-split-7',
          'slot-g33-split-8',
          'slot-g33-split-9',
        ],
      },
    ],
    version: 1,
    sortOrder: 7,
    published: true,
  },
  {
    id: 'hybrid-classic3-horizon-sandwich-9',
    slug: 'hybrid-classic3-horizon-sandwich',
    name: 'Horizon Sandwich Triptych',
    category: 'hybrid',
    description:
      'Architectural grid aligning 3 central A4 triptych panels with upper and lower horizontal A5 companion rows.',
    badge: 'Architectural Grid',
    wallWidthMm: 780,
    wallHeightMm: 743,
    coverageLabel: '66 × 62 cm',
    physicalPrintCount: 9,
    logicalArtworkCount: 7,
    recommendedRoom: 'Dining Room / Living Room Feature Wall',
    recommendedWallWidth: '1.6 – 2.2 m',
    recommendedThemes: ['Photography', 'Travel', 'Cars', 'Cinema', 'DC'],
    basePrice: 2399,
    compareAtPrice: 3299,
    slots: [
      {
        id: 'slot-c3h9-top-1',
        slotType: 'accent',
        x: 0.0769,
        y: 0.0808,
        width: 0.2692,
        height: 0.1992,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Top Col 1 Accent (A5)',
      },
      {
        id: 'slot-c3h9-split-1',
        slotType: 'hero-panel',
        x: 0.0769,
        y: 0.3001,
        width: 0.2692,
        height: 0.3997,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Center Triptych Panel 1/3 (A4)',
        splitGroupId: 'split-c3h9-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-c3h9-bot-1',
        slotType: 'accent',
        x: 0.0769,
        y: 0.7201,
        width: 0.2692,
        height: 0.1992,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Bottom Col 1 Accent (A5)',
      },
      {
        id: 'slot-c3h9-top-2',
        slotType: 'accent',
        x: 0.3654,
        y: 0.0808,
        width: 0.2692,
        height: 0.1992,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Top Col 2 Accent (A5)',
      },
      {
        id: 'slot-c3h9-split-2',
        slotType: 'hero-panel',
        x: 0.3654,
        y: 0.3001,
        width: 0.2692,
        height: 0.3997,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Center Triptych Panel 2/3 (A4)',
        splitGroupId: 'split-c3h9-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-c3h9-bot-2',
        slotType: 'accent',
        x: 0.3654,
        y: 0.7201,
        width: 0.2692,
        height: 0.1992,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Bottom Col 2 Accent (A5)',
      },
      {
        id: 'slot-c3h9-top-3',
        slotType: 'accent',
        x: 0.6538,
        y: 0.0808,
        width: 0.2692,
        height: 0.1992,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Top Col 3 Accent (A5)',
      },
      {
        id: 'slot-c3h9-split-3',
        slotType: 'hero-panel',
        x: 0.6538,
        y: 0.3001,
        width: 0.2692,
        height: 0.3997,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Center Triptych Panel 3/3 (A4)',
        splitGroupId: 'split-c3h9-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-c3h9-bot-3',
        slotType: 'accent',
        x: 0.6538,
        y: 0.7201,
        width: 0.2692,
        height: 0.1992,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Bottom Col 3 Accent (A5)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-c3h9-hero',
        name: 'Classic 3-Piece Horizontal Split',
        panelCount: 3,
        orientation: 'portrait',
        physicalSize: 'A4',
        slotIds: ['slot-c3h9-split-1', 'slot-c3h9-split-2', 'slot-c3h9-split-3'],
      },
    ],
    version: 1,
    sortOrder: 8,
    published: true,
  },
  {
    id: 'hybrid-classic4-cinema-8',
    slug: 'hybrid-classic4-cinema',
    name: 'Cinema-4 Widescreen Enclave',
    category: 'hybrid',
    description:
      'Cinematic 4-panel split horizon crowned by dual horizontal A4s and flanked by vertical framing pillars.',
    badge: 'Cinema Widescreen',
    wallWidthMm: 1207,
    wallHeightMm: 599,
    coverageLabel: '109 × 48 cm',
    physicalPrintCount: 8,
    logicalArtworkCount: 5,
    recommendedRoom: 'Entertainment Console / Living Room',
    recommendedWallWidth: '1.8 – 2.4 m',
    recommendedThemes: ['Cars', 'Marvel', 'Cinema', 'Space', 'Anime'],
    basePrice: 2299,
    compareAtPrice: 3099,
    slots: [
      {
        id: 'slot-c4c8-top-1',
        slotType: 'accent',
        x: 0.2477,
        y: 0.1002,
        width: 0.2461,
        height: 0.3506,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Top Left Accent (A4)',
      },
      {
        id: 'slot-c4c8-top-2',
        slotType: 'accent',
        x: 0.5062,
        y: 0.1002,
        width: 0.2461,
        height: 0.3506,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Top Right Accent (A4)',
      },
      {
        id: 'slot-c4c8-left-a4',
        slotType: 'accent',
        x: 0.0497,
        y: 0.4032,
        width: 0.174,
        height: 0.4958,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Pillar (A4)',
      },
      {
        id: 'slot-c4c8-split-1',
        slotType: 'hero-panel',
        x: 0.2361,
        y: 0.4758,
        width: 0.1226,
        height: 0.3506,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Cinema Panel 1/4 (A5)',
        splitGroupId: 'split-c4c8-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-c4c8-split-2',
        slotType: 'hero-panel',
        x: 0.3712,
        y: 0.4758,
        width: 0.1226,
        height: 0.3506,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Cinema Panel 2/4 (A5)',
        splitGroupId: 'split-c4c8-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-c4c8-split-3',
        slotType: 'hero-panel',
        x: 0.5062,
        y: 0.4758,
        width: 0.1226,
        height: 0.3506,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Cinema Panel 3/4 (A5)',
        splitGroupId: 'split-c4c8-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-c4c8-split-4',
        slotType: 'hero-panel',
        x: 0.6413,
        y: 0.4758,
        width: 0.1226,
        height: 0.3506,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Cinema Panel 4/4 (A5)',
        splitGroupId: 'split-c4c8-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-c4c8-right-a4',
        slotType: 'accent',
        x: 0.7763,
        y: 0.4032,
        width: 0.174,
        height: 0.4958,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Pillar (A4)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-c4c8-hero',
        name: 'Classic 4-Piece Horizontal Split',
        panelCount: 4,
        orientation: 'portrait',
        physicalSize: 'A5',
        slotIds: [
          'slot-c4c8-split-1',
          'slot-c4c8-split-2',
          'slot-c4c8-split-3',
          'slot-c4c8-split-4',
        ],
      },
    ],
    version: 1,
    sortOrder: 9,
    published: true,
  },
  {
    id: 'hybrid-classic5-grand-panorama-9',
    slug: 'hybrid-classic5-grand-panorama',
    name: 'Grand 5-Panel Panorama with 13×19 Wings',
    category: 'hybrid',
    description:
      'Ultrawide 5-panel split artwork crowned by dual panoramic A3s and flanked by 13×19" grand monuments.',
    badge: 'Epic Ultrawide',
    wallWidthMm: 1665,
    wallHeightMm: 642,
    coverageLabel: '155 × 52 cm',
    physicalPrintCount: 9,
    logicalArtworkCount: 5,
    recommendedRoom: 'Grand Living Room / Feature Wall / Hallway',
    recommendedWallWidth: '2.2 – 2.8 m',
    recommendedThemes: ['Cars', 'Nature', 'Space', 'Marvel', 'Cinema'],
    basePrice: 3499,
    compareAtPrice: 4799,
    slots: [
      {
        id: 'slot-c5g9-arch-left',
        slotType: 'hero',
        x: 0.036,
        y: 0.1238,
        width: 0.1982,
        height: 0.7523,
        size: '13x19',
        physicalWidthMm: 330,
        physicalHeightMm: 483,
        orientation: 'portrait',
        required: true,
        label: 'Left Monument (13×19")',
      },
      {
        id: 'slot-c5g9-top-1',
        slotType: 'accent',
        x: 0.2432,
        y: 0.0935,
        width: 0.2523,
        height: 0.4626,
        size: 'A3',
        physicalWidthMm: 420,
        physicalHeightMm: 297,
        orientation: 'landscape',
        required: true,
        label: 'Upper Panoramic Left (A3)',
      },
      {
        id: 'slot-c5g9-top-2',
        slotType: 'accent',
        x: 0.5045,
        y: 0.0935,
        width: 0.2523,
        height: 0.4626,
        size: 'A3',
        physicalWidthMm: 420,
        physicalHeightMm: 297,
        orientation: 'landscape',
        required: true,
        label: 'Upper Panoramic Right (A3)',
      },
      {
        id: 'slot-c5g9-split-1',
        slotType: 'hero-panel',
        x: 0.2598,
        y: 0.5794,
        width: 0.0889,
        height: 0.3271,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Ultrawide Panel 1/5 (A5)',
        splitGroupId: 'split-c5g9-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-c5g9-split-2',
        slotType: 'hero-panel',
        x: 0.3577,
        y: 0.5794,
        width: 0.0889,
        height: 0.3271,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Ultrawide Panel 2/5 (A5)',
        splitGroupId: 'split-c5g9-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-c5g9-split-3',
        slotType: 'hero-panel',
        x: 0.4556,
        y: 0.5794,
        width: 0.0889,
        height: 0.3271,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Ultrawide Panel 3/5 (A5)',
        splitGroupId: 'split-c5g9-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-c5g9-split-4',
        slotType: 'hero-panel',
        x: 0.5535,
        y: 0.5794,
        width: 0.0889,
        height: 0.3271,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Ultrawide Panel 4/5 (A5)',
        splitGroupId: 'split-c5g9-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-c5g9-split-5',
        slotType: 'hero-panel',
        x: 0.6514,
        y: 0.5794,
        width: 0.0889,
        height: 0.3271,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Ultrawide Panel 5/5 (A5)',
        splitGroupId: 'split-c5g9-hero',
        panelIndex: 4,
      },
      {
        id: 'slot-c5g9-arch-right',
        slotType: 'hero',
        x: 0.7658,
        y: 0.1238,
        width: 0.1982,
        height: 0.7523,
        size: '13x19',
        physicalWidthMm: 330,
        physicalHeightMm: 483,
        orientation: 'portrait',
        required: true,
        label: 'Right Monument (13×19")',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-c5g9-hero',
        name: 'Classic 5-Piece Ultrawide Split',
        panelCount: 5,
        orientation: 'portrait',
        physicalSize: 'A5',
        slotIds: [
          'slot-c5g9-split-1',
          'slot-c5g9-split-2',
          'slot-c5g9-split-3',
          'slot-c5g9-split-4',
          'slot-c5g9-split-5',
        ],
      },
    ],
    version: 1,
    sortOrder: 10,
    published: true,
  },
  {
    id: 'hybrid-vertical3-totem-flank-7',
    slug: 'hybrid-vertical3-totem-flank',
    name: 'Vertical Totem Tower with Dual Flanks',
    category: 'hybrid',
    description:
      'Tall 3-tier vertical split totem (stacked A4 horizontals) flanked symmetrically by dual vertical A4 columns.',
    badge: 'Vertical Totem',
    wallWidthMm: 867,
    wallHeightMm: 780,
    coverageLabel: '75 × 66 cm',
    physicalPrintCount: 7,
    logicalArtworkCount: 5,
    recommendedRoom: 'Entryway / Pillar Wall / Reading Nook',
    recommendedWallWidth: '1.2 – 1.6 m',
    recommendedThemes: ['Minimalist', 'Anime', 'Travel', 'Art', 'Gaming'],
    basePrice: 2099,
    compareAtPrice: 2899,
    slots: [
      {
        id: 'slot-v3t7-left-top',
        slotType: 'accent',
        x: 0.0692,
        y: 0.1096,
        width: 0.2422,
        height: 0.3808,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Upper (A4)',
      },
      {
        id: 'slot-v3t7-left-bot',
        slotType: 'accent',
        x: 0.0692,
        y: 0.5096,
        width: 0.2422,
        height: 0.3808,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Lower (A4)',
      },
      {
        id: 'slot-v3t7-split-1',
        slotType: 'hero-panel',
        x: 0.3287,
        y: 0.0769,
        width: 0.3426,
        height: 0.2692,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Totem Tier 1/3 (A4)',
        splitGroupId: 'split-v3t7-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-v3t7-split-2',
        slotType: 'hero-panel',
        x: 0.3287,
        y: 0.3654,
        width: 0.3426,
        height: 0.2692,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Totem Tier 2/3 (A4)',
        splitGroupId: 'split-v3t7-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-v3t7-split-3',
        slotType: 'hero-panel',
        x: 0.3287,
        y: 0.6538,
        width: 0.3426,
        height: 0.2692,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Totem Tier 3/3 (A4)',
        splitGroupId: 'split-v3t7-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-v3t7-right-top',
        slotType: 'accent',
        x: 0.6886,
        y: 0.1096,
        width: 0.2422,
        height: 0.3808,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Upper (A4)',
      },
      {
        id: 'slot-v3t7-right-bot',
        slotType: 'accent',
        x: 0.6886,
        y: 0.5096,
        width: 0.2422,
        height: 0.3808,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Lower (A4)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-v3t7-hero',
        name: 'Vertical 3-Piece Stacked Split',
        panelCount: 3,
        orientation: 'landscape',
        physicalSize: 'A4',
        slotIds: ['slot-v3t7-split-1', 'slot-v3t7-split-2', 'slot-v3t7-split-3'],
      },
    ],
    version: 1,
    sortOrder: 11,
    published: true,
  },
  {
    id: 'hybrid-vertical4-monolith-8',
    slug: 'hybrid-vertical4-monolith',
    name: 'Monolith 4-Tier Spire with Quad Flanks',
    category: 'hybrid',
    description:
      '4-tier stacked horizontal A5 vertical split column framed symmetrically by vertical A4 flanking wings.',
    badge: 'Vertical Monolith',
    wallWidthMm: 780,
    wallHeightMm: 757,
    coverageLabel: '66 × 64 cm',
    physicalPrintCount: 8,
    logicalArtworkCount: 5,
    recommendedRoom: 'Studio / Hallway / Bedroom Column',
    recommendedWallWidth: '1.2 – 1.6 m',
    recommendedThemes: ['Anime', 'Gaming', 'Marvel', 'Cinema'],
    basePrice: 2199,
    compareAtPrice: 2999,
    slots: [
      {
        id: 'slot-v4m8-left-top',
        slotType: 'accent',
        x: 0.0769,
        y: 0.0978,
        width: 0.2692,
        height: 0.3923,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Upper (A4)',
      },
      {
        id: 'slot-v4m8-left-bot',
        slotType: 'accent',
        x: 0.0769,
        y: 0.5099,
        width: 0.2692,
        height: 0.3923,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Lower (A4)',
      },
      {
        id: 'slot-v4m8-split-1',
        slotType: 'hero-panel',
        x: 0.3654,
        y: 0.0793,
        width: 0.2692,
        height: 0.1955,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 1/4 (A5)',
        splitGroupId: 'split-v4m8-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-v4m8-split-2',
        slotType: 'hero-panel',
        x: 0.3654,
        y: 0.2946,
        width: 0.2692,
        height: 0.1955,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 2/4 (A5)',
        splitGroupId: 'split-v4m8-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-v4m8-split-3',
        slotType: 'hero-panel',
        x: 0.3654,
        y: 0.5099,
        width: 0.2692,
        height: 0.1955,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 3/4 (A5)',
        splitGroupId: 'split-v4m8-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-v4m8-split-4',
        slotType: 'hero-panel',
        x: 0.3654,
        y: 0.7252,
        width: 0.2692,
        height: 0.1955,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 4/4 (A5)',
        splitGroupId: 'split-v4m8-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-v4m8-right-top',
        slotType: 'accent',
        x: 0.6538,
        y: 0.0978,
        width: 0.2692,
        height: 0.3923,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Upper (A4)',
      },
      {
        id: 'slot-v4m8-right-bot',
        slotType: 'accent',
        x: 0.6538,
        y: 0.5099,
        width: 0.2692,
        height: 0.3923,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Lower (A4)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-v4m8-hero',
        name: 'Vertical 4-Piece Stacked Split',
        panelCount: 4,
        orientation: 'landscape',
        physicalSize: 'A5',
        slotIds: [
          'slot-v4m8-split-1',
          'slot-v4m8-split-2',
          'slot-v4m8-split-3',
          'slot-v4m8-split-4',
        ],
      },
    ],
    version: 1,
    sortOrder: 12,
    published: true,
  },
  {
    id: 'hybrid-stepped-triptych-quadwing-9',
    slug: 'hybrid-stepped-triptych-quadwing',
    name: 'Stepped Triptych Salon Enclave',
    category: 'hybrid',
    description:
      'Complete salon ensemble enclosing a 3-panel stepped split with dual A5 wings and A4 horizontal header/footer anchors.',
    badge: 'Salon Enclave',
    wallWidthMm: 928,
    wallHeightMm: 849,
    coverageLabel: '81 × 73 cm',
    physicalPrintCount: 9,
    logicalArtworkCount: 7,
    recommendedRoom: 'Master Bedroom / Living Room Gallery',
    recommendedWallWidth: '1.6 – 2.2 m',
    recommendedThemes: ['Anime', 'Marvel', 'DC', 'Gaming', 'Cars'],
    basePrice: 2499,
    compareAtPrice: 3399,
    slots: [
      {
        id: 'slot-stq9-left-top',
        slotType: 'accent',
        x: 0.0647,
        y: 0.2438,
        width: 0.1595,
        height: 0.2473,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Left Upper Wing (A5)',
      },
      {
        id: 'slot-stq9-left-bot',
        slotType: 'accent',
        x: 0.0647,
        y: 0.5088,
        width: 0.1595,
        height: 0.2473,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Left Lower Wing (A5)',
      },
      {
        id: 'slot-stq9-top-a4',
        slotType: 'accent',
        x: 0.34,
        y: 0.0707,
        width: 0.32,
        height: 0.2473,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Upper Header (A4)',
      },
      {
        id: 'slot-stq9-split-1',
        slotType: 'hero-panel',
        x: 0.2403,
        y: 0.3651,
        width: 0.1638,
        height: 0.2697,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Left 6×9" (152×229mm)',
        splitGroupId: 'split-stq9-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-stq9-split-2',
        slotType: 'hero-panel',
        x: 0.4181,
        y: 0.3357,
        width: 0.1638,
        height: 0.3286,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 279,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Center 6×11" (152×279mm)',
        splitGroupId: 'split-stq9-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-stq9-split-3',
        slotType: 'hero-panel',
        x: 0.5959,
        y: 0.3651,
        width: 0.1638,
        height: 0.2697,
        size: 'CUSTOM',
        physicalWidthMm: 152,
        physicalHeightMm: 229,
        orientation: 'portrait',
        required: true,
        label: 'Stepped Right 6×9" (152×229mm)',
        splitGroupId: 'split-stq9-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-stq9-bot-a4',
        slotType: 'accent',
        x: 0.34,
        y: 0.682,
        width: 0.32,
        height: 0.2473,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Lower Base (A4)',
      },
      {
        id: 'slot-stq9-right-top',
        slotType: 'accent',
        x: 0.7759,
        y: 0.2438,
        width: 0.1595,
        height: 0.2473,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Right Upper Wing (A5)',
      },
      {
        id: 'slot-stq9-right-bot',
        slotType: 'accent',
        x: 0.7759,
        y: 0.5088,
        width: 0.1595,
        height: 0.2473,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Right Lower Wing (A5)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-stq9-hero',
        name: 'Stepped 3-Piece Split Artwork',
        panelCount: 3,
        orientation: 'portrait',
        physicalSize: 'CUSTOM',
        slotIds: ['slot-stq9-split-1', 'slot-stq9-split-2', 'slot-stq9-split-3'],
        staggered: true,
      },
    ],
    version: 1,
    sortOrder: 13,
    published: true,
  },
  {
    id: 'hybrid-grid2x2-windowpane-8',
    slug: 'hybrid-grid2x2-windowpane',
    name: 'Windowpane 2×2 Surrounded Salon',
    category: 'hybrid',
    description:
      'Landscape 2×2 grid split in A5 surrounded on all 4 cardinal directions by curated A4 standard frames.',
    badge: 'Surrounded Salon',
    wallWidthMm: 1005,
    wallHeightMm: 881,
    coverageLabel: '89 × 76 cm',
    physicalPrintCount: 8,
    logicalArtworkCount: 5,
    recommendedRoom: 'Studio / Dining Room / Reception Wall',
    recommendedWallWidth: '1.6 – 2.2 m',
    recommendedThemes: ['Photography', 'Travel', 'Art', 'Nature', 'Cinema'],
    basePrice: 2299,
    compareAtPrice: 3099,
    slots: [
      {
        id: 'slot-g2w8-top-a4',
        slotType: 'accent',
        x: 0.3522,
        y: 0.0681,
        width: 0.2955,
        height: 0.2384,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Top Accent (A4)',
      },
      {
        id: 'slot-g2w8-left-a4',
        slotType: 'accent',
        x: 0.0597,
        y: 0.3314,
        width: 0.209,
        height: 0.3371,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Pillar (A4)',
      },
      {
        id: 'slot-g2w8-split-1',
        slotType: 'hero-panel',
        x: 0.2836,
        y: 0.3235,
        width: 0.209,
        height: 0.168,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Grid Panel 1/4 Top-Left (A5)',
        splitGroupId: 'split-g2w8-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-g2w8-split-2',
        slotType: 'hero-panel',
        x: 0.5075,
        y: 0.3235,
        width: 0.209,
        height: 0.168,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Grid Panel 2/4 Top-Right (A5)',
        splitGroupId: 'split-g2w8-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-g2w8-split-3',
        slotType: 'hero-panel',
        x: 0.2836,
        y: 0.5085,
        width: 0.209,
        height: 0.168,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Grid Panel 3/4 Bot-Left (A5)',
        splitGroupId: 'split-g2w8-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-g2w8-split-4',
        slotType: 'hero-panel',
        x: 0.5075,
        y: 0.5085,
        width: 0.209,
        height: 0.168,
        size: 'A5',
        physicalWidthMm: 210,
        physicalHeightMm: 148,
        orientation: 'landscape',
        required: true,
        label: 'Grid Panel 4/4 Bot-Right (A5)',
        splitGroupId: 'split-g2w8-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-g2w8-right-a4',
        slotType: 'accent',
        x: 0.7313,
        y: 0.3314,
        width: 0.209,
        height: 0.3371,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Pillar (A4)',
      },
      {
        id: 'slot-g2w8-bot-a4',
        slotType: 'accent',
        x: 0.3522,
        y: 0.6935,
        width: 0.2955,
        height: 0.2384,
        size: 'A4',
        physicalWidthMm: 297,
        physicalHeightMm: 210,
        orientation: 'landscape',
        required: true,
        label: 'Bottom Base (A4)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-g2w8-hero',
        name: '2×2 Landscape Windowpane Split',
        panelCount: 4,
        orientation: 'landscape',
        physicalSize: 'A5',
        slotIds: [
          'slot-g2w8-split-1',
          'slot-g2w8-split-2',
          'slot-g2w8-split-3',
          'slot-g2w8-split-4',
        ],
      },
    ],
    version: 1,
    sortOrder: 14,
    published: true,
  },
  {
    id: 'hybrid-classic3-cinema-a3-7',
    slug: 'hybrid-classic3-cinema-a3',
    name: 'Grand Cinema A3 Triptych with A5 Wings',
    category: 'hybrid',
    description:
      'Large-format A3 triptych split artwork flanked symmetrically by vertical A5 gallery wings.',
    badge: 'Grand Triptych',
    wallWidthMm: 1367,
    wallHeightMm: 555,
    coverageLabel: '125 × 44 cm',
    physicalPrintCount: 7,
    logicalArtworkCount: 5,
    recommendedRoom: 'Media Console / Main Feature Wall',
    recommendedWallWidth: '1.8 – 2.4 m',
    recommendedThemes: ['Cinema', 'Cars', 'Marvel', 'DC', 'Space'],
    basePrice: 2599,
    compareAtPrice: 3499,
    slots: [
      {
        id: 'slot-c3a7-left-top',
        slotType: 'accent',
        x: 0.0439,
        y: 0.1081,
        width: 0.1083,
        height: 0.3784,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Left Upper Wing (A5)',
      },
      {
        id: 'slot-c3a7-left-bot',
        slotType: 'accent',
        x: 0.0439,
        y: 0.5135,
        width: 0.1083,
        height: 0.3784,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Left Lower Wing (A5)',
      },
      {
        id: 'slot-c3a7-split-1',
        slotType: 'hero-panel',
        x: 0.1631,
        y: 0.1216,
        width: 0.2173,
        height: 0.7568,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Cinema A3 Panel 1/3',
        splitGroupId: 'split-c3a7-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-c3a7-split-2',
        slotType: 'hero-panel',
        x: 0.3914,
        y: 0.1216,
        width: 0.2173,
        height: 0.7568,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Cinema A3 Panel 2/3',
        splitGroupId: 'split-c3a7-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-c3a7-split-3',
        slotType: 'hero-panel',
        x: 0.6196,
        y: 0.1216,
        width: 0.2173,
        height: 0.7568,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Cinema A3 Panel 3/3',
        splitGroupId: 'split-c3a7-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-c3a7-right-top',
        slotType: 'accent',
        x: 0.8478,
        y: 0.1081,
        width: 0.1083,
        height: 0.3784,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Right Upper Wing (A5)',
      },
      {
        id: 'slot-c3a7-right-bot',
        slotType: 'accent',
        x: 0.8478,
        y: 0.5135,
        width: 0.1083,
        height: 0.3784,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Right Lower Wing (A5)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-c3a7-hero',
        name: 'Grand A3 3-Piece Triptych Split',
        panelCount: 3,
        orientation: 'portrait',
        physicalSize: 'A3',
        slotIds: ['slot-c3a7-split-1', 'slot-c3a7-split-2', 'slot-c3a7-split-3'],
      },
    ],
    version: 1,
    sortOrder: 15,
    published: true,
  },
  {
    id: 'hybrid-vertical5-spire-11',
    slug: 'hybrid-vertical5-spire',
    name: '5-Tier High-Rise Spire Gallery',
    category: 'hybrid',
    description: 'Tall 5-tier vertical split spire framed by towering A5 and A6 columns.',
    badge: 'High-Rise Spire',
    wallWidthMm: 594,
    wallHeightMm: 693,
    coverageLabel: '47 × 57 cm',
    physicalPrintCount: 11,
    logicalArtworkCount: 7,
    recommendedRoom: 'Hallway / Living Room Vertical Space',
    recommendedWallWidth: '1.2 – 1.6 m',
    recommendedThemes: ['Cyberpunk', 'Anime', 'Travel', 'Art'],
    basePrice: 2599,
    compareAtPrice: 3499,
    slots: [
      {
        id: 'slot-v5s11-left-1',
        slotType: 'accent',
        x: 0.101,
        y: 0.0996,
        width: 0.2492,
        height: 0.303,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Left Pillar Top (A5)',
      },
      {
        id: 'slot-v5s11-left-2',
        slotType: 'accent',
        x: 0.101,
        y: 0.4242,
        width: 0.2492,
        height: 0.303,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Left Pillar Mid (A5)',
      },
      {
        id: 'slot-v5s11-left-3',
        slotType: 'accent',
        x: 0.101,
        y: 0.7489,
        width: 0.2492,
        height: 0.1515,
        size: 'A6',
        physicalWidthMm: 148,
        physicalHeightMm: 105,
        orientation: 'landscape',
        required: true,
        label: 'Left Pillar Base (A6)',
      },
      {
        id: 'slot-v5s11-split-1',
        slotType: 'hero-panel',
        x: 0.3754,
        y: 0.0866,
        width: 0.2492,
        height: 0.1515,
        size: 'A6',
        physicalWidthMm: 148,
        physicalHeightMm: 105,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 1/5 (A6)',
        splitGroupId: 'split-v5s11-hero',
        panelIndex: 0,
      },
      {
        id: 'slot-v5s11-split-2',
        slotType: 'hero-panel',
        x: 0.3754,
        y: 0.2554,
        width: 0.2492,
        height: 0.1515,
        size: 'A6',
        physicalWidthMm: 148,
        physicalHeightMm: 105,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 2/5 (A6)',
        splitGroupId: 'split-v5s11-hero',
        panelIndex: 1,
      },
      {
        id: 'slot-v5s11-split-3',
        slotType: 'hero-panel',
        x: 0.3754,
        y: 0.4242,
        width: 0.2492,
        height: 0.1515,
        size: 'A6',
        physicalWidthMm: 148,
        physicalHeightMm: 105,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 3/5 (A6)',
        splitGroupId: 'split-v5s11-hero',
        panelIndex: 2,
      },
      {
        id: 'slot-v5s11-split-4',
        slotType: 'hero-panel',
        x: 0.3754,
        y: 0.5931,
        width: 0.2492,
        height: 0.1515,
        size: 'A6',
        physicalWidthMm: 148,
        physicalHeightMm: 105,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 4/5 (A6)',
        splitGroupId: 'split-v5s11-hero',
        panelIndex: 3,
      },
      {
        id: 'slot-v5s11-split-5',
        slotType: 'hero-panel',
        x: 0.3754,
        y: 0.7619,
        width: 0.2492,
        height: 0.1515,
        size: 'A6',
        physicalWidthMm: 148,
        physicalHeightMm: 105,
        orientation: 'landscape',
        required: true,
        label: 'Spire Tier 5/5 (A6)',
        splitGroupId: 'split-v5s11-hero',
        panelIndex: 4,
      },
      {
        id: 'slot-v5s11-right-1',
        slotType: 'accent',
        x: 0.6498,
        y: 0.0996,
        width: 0.2492,
        height: 0.303,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Right Pillar Top (A5)',
      },
      {
        id: 'slot-v5s11-right-2',
        slotType: 'accent',
        x: 0.6498,
        y: 0.4242,
        width: 0.2492,
        height: 0.303,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        required: true,
        label: 'Right Pillar Mid (A5)',
      },
      {
        id: 'slot-v5s11-right-3',
        slotType: 'accent',
        x: 0.6498,
        y: 0.7489,
        width: 0.2492,
        height: 0.1515,
        size: 'A6',
        physicalWidthMm: 148,
        physicalHeightMm: 105,
        orientation: 'landscape',
        required: true,
        label: 'Right Pillar Base (A6)',
      },
    ],
    splitGroups: [
      {
        splitGroupId: 'split-v5s11-hero',
        name: 'Vertical 5-Piece Stacked Split',
        panelCount: 5,
        orientation: 'landscape',
        physicalSize: 'A6',
        slotIds: [
          'slot-v5s11-split-1',
          'slot-v5s11-split-2',
          'slot-v5s11-split-3',
          'slot-v5s11-split-4',
          'slot-v5s11-split-5',
        ],
      },
    ],
    version: 1,
    sortOrder: 16,
    published: true,
  },
  {
    id: 'compact-01',
    slug: 'compact',
    name: '01 — Compact',
    description:
      'An intimate 5-piece composition with an A3 focal hero anchored by four offset A4 supporting works.',
    badge: 'Popular Starter',
    wallWidthMm: 1350,
    wallHeightMm: 1150,
    coverageLabel: '135 × 115 cm',
    physicalPrintCount: 5,
    logicalArtworkCount: 5,
    recommendedRoom: 'Bedroom / Studio Corner / Entryway',
    recommendedWallWidth: '1.6 – 2.0 m',
    recommendedThemes: ['Minimal', 'Quotes', 'Aesthetic', 'Anime', 'Gaming'],
    basePrice: 699,
    compareAtPrice: 899,
    published: true,
    version: 1,
    sortOrder: 20,
    splitGroups: [],
    slots: [
      {
        id: 'slot-c-hero',
        slotType: 'hero',
        x: 0.39,
        y: 0.3174,
        width: 0.22,
        height: 0.3652,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Hero Center (A3)',
      },
      {
        id: 'slot-c-top',
        slotType: 'support',
        x: 0.4222,
        y: 0.0374,
        width: 0.1556,
        height: 0.2583,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Top Accent (A4)',
      },
      {
        id: 'slot-c-bottom',
        slotType: 'support',
        x: 0.4222,
        y: 0.7043,
        width: 0.1556,
        height: 0.2583,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Bottom Anchor (A4)',
      },
      {
        id: 'slot-c-left',
        slotType: 'support',
        x: 0.2159,
        y: 0.3709,
        width: 0.1556,
        height: 0.2583,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Left Balance (A4)',
      },
      {
        id: 'slot-c-right',
        slotType: 'support',
        x: 0.6285,
        y: 0.3709,
        width: 0.1556,
        height: 0.2583,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Right Balance (A4)',
      },
    ],
    category: 'gallery',
  },
  {
    id: 'classic-02',
    slug: 'classic',
    name: '02 — Classic',
    description:
      'An 8-print exhibition grid with rhythmic staggered heights that avoids mechanical rigidity.',
    badge: 'Timeless',
    wallWidthMm: 1450,
    wallHeightMm: 980,
    coverageLabel: '145 × 98 cm',
    physicalPrintCount: 8,
    logicalArtworkCount: 8,
    recommendedRoom: 'Living Room / Home Office',
    recommendedWallWidth: '1.8 – 2.4 m',
    recommendedThemes: ['Photography', 'Retro', 'Movies', 'Music', 'Quotes'],
    basePrice: 899,
    compareAtPrice: 1199,
    published: true,
    version: 1,
    sortOrder: 21,
    splitGroups: [],
    slots: [
      {
        id: 'slot-cl-1',
        slotType: 'support',
        x: 0.12,
        y: 0.12,
        width: 0.145,
        height: 0.303,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Top Left (A4)',
      },
      {
        id: 'slot-cl-2',
        slotType: 'support',
        x: 0.12,
        y: 0.52,
        width: 0.145,
        height: 0.303,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Bottom Left (A4)',
      },
      {
        id: 'slot-cl-3',
        slotType: 'hero',
        x: 0.34,
        y: 0.08,
        width: 0.145,
        height: 0.303,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Upper Mid-Left (A4)',
      },
      {
        id: 'slot-cl-4',
        slotType: 'hero',
        x: 0.34,
        y: 0.48,
        width: 0.145,
        height: 0.303,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Lower Mid-Left (A4)',
      },
      {
        id: 'slot-cl-5',
        slotType: 'hero',
        x: 0.52,
        y: 0.18,
        width: 0.145,
        height: 0.303,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Upper Mid-Right (A4)',
      },
      {
        id: 'slot-cl-6',
        slotType: 'hero',
        x: 0.52,
        y: 0.58,
        width: 0.145,
        height: 0.303,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Lower Mid-Right (A4)',
      },
      {
        id: 'slot-cl-7',
        slotType: 'support',
        x: 0.74,
        y: 0.12,
        width: 0.145,
        height: 0.303,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Top Right (A4)',
      },
      {
        id: 'slot-cl-8',
        slotType: 'support',
        x: 0.74,
        y: 0.52,
        width: 0.145,
        height: 0.303,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Bottom Right (A4)',
      },
    ],
    category: 'gallery',
  },
  {
    id: 'studio-03',
    slug: 'studio',
    name: '03 — Studio',
    description:
      'A curated 10-piece creative arrangement mixing A3, A4, and A5 with subtle vertical offsets.',
    badge: 'Designer Pick',
    wallWidthMm: 1550,
    wallHeightMm: 1050,
    coverageLabel: '155 × 105 cm',
    physicalPrintCount: 10,
    logicalArtworkCount: 10,
    recommendedRoom: 'Studio / Creative Space / Lounge',
    recommendedWallWidth: '2.0 – 2.6 m',
    recommendedThemes: ['Aesthetic', 'Minimal', 'Dark', 'Kollywood', 'Gaming'],
    basePrice: 1199,
    compareAtPrice: 1599,
    published: true,
    version: 1,
    sortOrder: 22,
    splitGroups: [],
    slots: [
      {
        id: 'slot-st-top1',
        slotType: 'accent',
        x: 0.39,
        y: 0.05,
        width: 0.095,
        height: 0.2,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Top Accent 1 (A5)',
      },
      {
        id: 'slot-st-top2',
        slotType: 'accent',
        x: 0.515,
        y: 0.05,
        width: 0.095,
        height: 0.2,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Top Accent 2 (A5)',
      },
      {
        id: 'slot-st-left-a4',
        slotType: 'support',
        x: 0.16,
        y: 0.26,
        width: 0.135,
        height: 0.283,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Mid Left (A4)',
      },
      {
        id: 'slot-st-hero',
        slotType: 'hero',
        x: 0.375,
        y: 0.28,
        width: 0.192,
        height: 0.4,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Central Focal (A3)',
      },
      {
        id: 'slot-st-right-a4',
        slotType: 'support',
        x: 0.69,
        y: 0.26,
        width: 0.135,
        height: 0.283,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Mid Right (A4)',
      },
      {
        id: 'slot-st-left-a5',
        slotType: 'accent',
        x: 0.18,
        y: 0.59,
        width: 0.095,
        height: 0.2,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Lower Left (A5)',
      },
      {
        id: 'slot-st-mid-a4',
        slotType: 'support',
        x: 0.32,
        y: 0.7,
        width: 0.135,
        height: 0.283,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Lower Mid (A4)',
      },
      {
        id: 'slot-st-right-a5',
        slotType: 'accent',
        x: 0.71,
        y: 0.59,
        width: 0.095,
        height: 0.2,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Lower Right (A5)',
      },
      {
        id: 'slot-st-bot-mid',
        slotType: 'accent',
        x: 0.54,
        y: 0.72,
        width: 0.095,
        height: 0.2,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Bottom Accent (A5)',
      },
      {
        id: 'slot-st-side-a5',
        slotType: 'accent',
        x: 0.83,
        y: 0.38,
        width: 0.095,
        height: 0.2,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Far Right Accent (A5)',
      },
    ],
    category: 'gallery',
  },
  {
    id: 'matrix-3x3-18',
    slug: 'matrix-grid',
    name: '18 — Matrix Grid 3×3',
    description:
      'A museum-grade 3×3 architectural grid of 9 A4 artworks with disciplined 25mm spacing. Clean, modern, and mathematically harmonious.',
    badge: 'Museum Grid',
    wallWidthMm: 1450,
    wallHeightMm: 1200,
    coverageLabel: '145 × 120 cm',
    physicalPrintCount: 9,
    logicalArtworkCount: 9,
    recommendedRoom: 'Studio / Dining / Office / Gallery Hall',
    recommendedWallWidth: '1.8 – 2.4 m',
    recommendedThemes: ['Minimal', 'Photography', 'Quotes', 'Cars', 'Music'],
    basePrice: 1149,
    compareAtPrice: 1499,
    published: true,
    version: 1,
    sortOrder: 23,
    splitGroups: [],
    slots: [
      {
        id: 'slot-mx-1',
        slotType: 'support',
        x: 0.2655,
        y: 0.1079,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: false,
        label: 'Grid Panel 1 (Row 1, Col 1)',
      },
      {
        id: 'slot-mx-2',
        slotType: 'support',
        x: 0.4276,
        y: 0.1079,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: false,
        label: 'Grid Panel 2 (Row 1, Col 2)',
      },
      {
        id: 'slot-mx-3',
        slotType: 'support',
        x: 0.5897,
        y: 0.1079,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: false,
        label: 'Grid Panel 3 (Row 1, Col 3)',
      },
      {
        id: 'slot-mx-4',
        slotType: 'support',
        x: 0.2655,
        y: 0.3762,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: false,
        label: 'Grid Panel 4 (Row 2, Col 1)',
      },
      {
        id: 'slot-mx-5',
        slotType: 'hero',
        x: 0.4276,
        y: 0.3762,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: true,
        label: 'Grid Panel 5 (Row 2, Col 2)',
      },
      {
        id: 'slot-mx-6',
        slotType: 'support',
        x: 0.5897,
        y: 0.3762,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: false,
        label: 'Grid Panel 6 (Row 2, Col 3)',
      },
      {
        id: 'slot-mx-7',
        slotType: 'support',
        x: 0.2655,
        y: 0.6446,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: false,
        label: 'Grid Panel 7 (Row 3, Col 1)',
      },
      {
        id: 'slot-mx-8',
        slotType: 'support',
        x: 0.4276,
        y: 0.6446,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: false,
        label: 'Grid Panel 8 (Row 3, Col 2)',
      },
      {
        id: 'slot-mx-9',
        slotType: 'support',
        x: 0.5897,
        y: 0.6446,
        width: 0.1448,
        height: 0.2475,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        required: false,
        label: 'Grid Panel 9 (Row 3, Col 3)',
      },
    ],
    category: 'gallery',
  },
  {
    id: 'salon-asymmetric-19',
    slug: 'salon-asymmetric',
    name: '19 — Salon Asymmetric',
    description:
      'Curated Parisian salon gallery arrangement. Deliberately offset heights and mixed A3, A4, and A5 frames create an organic collector wall.',
    badge: 'Parisian Eclectic',
    wallWidthMm: 1750,
    wallHeightMm: 1100,
    coverageLabel: '175 × 110 cm',
    physicalPrintCount: 11,
    logicalArtworkCount: 11,
    recommendedRoom: 'Living Room / Creative Studio / Lounge',
    recommendedWallWidth: '2.1 – 2.8 m',
    recommendedThemes: ['Aesthetic', 'Vintage', 'Anime', 'Street', 'Music'],
    basePrice: 1299,
    compareAtPrice: 1699,
    published: true,
    version: 1,
    sortOrder: 24,
    splitGroups: [],
    slots: [
      {
        id: 'slot-sl-1',
        slotType: 'hero',
        x: 0.3314,
        y: 0.2273,
        width: 0.1697,
        height: 0.3818,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Hero Core 1 (A3)',
      },
      {
        id: 'slot-sl-2',
        slotType: 'hero',
        x: 0.5154,
        y: 0.1455,
        width: 0.1697,
        height: 0.3818,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Hero Core 2 (A3)',
      },
      {
        id: 'slot-sl-3',
        slotType: 'support',
        x: 0.1971,
        y: 0.1091,
        width: 0.12,
        height: 0.27,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Left Upper Support (A4)',
      },
      {
        id: 'slot-sl-4',
        slotType: 'support',
        x: 0.1971,
        y: 0.4018,
        width: 0.12,
        height: 0.27,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Left Mid Support (A4)',
      },
      {
        id: 'slot-sl-5',
        slotType: 'support',
        x: 0.6994,
        y: 0.2636,
        width: 0.12,
        height: 0.27,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Right Upper Support (A4)',
      },
      {
        id: 'slot-sl-6',
        slotType: 'support',
        x: 0.6994,
        y: 0.5564,
        width: 0.12,
        height: 0.27,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Right Lower Support (A4)',
      },
      {
        id: 'slot-sl-7',
        slotType: 'accent',
        x: 0.3314,
        y: 0.6318,
        width: 0.0846,
        height: 0.1909,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Base Accent 1 (A5)',
      },
      {
        id: 'slot-sl-8',
        slotType: 'accent',
        x: 0.4303,
        y: 0.6727,
        width: 0.0846,
        height: 0.1909,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Base Accent 2 (A5)',
      },
      {
        id: 'slot-sl-9',
        slotType: 'accent',
        x: 0.5291,
        y: 0.55,
        width: 0.0846,
        height: 0.1909,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Base Accent 3 (A5)',
      },
      {
        id: 'slot-sl-10',
        slotType: 'accent',
        x: 0.3314,
        y: 0.0136,
        width: 0.0846,
        height: 0.1909,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Top Accent (A5)',
      },
      {
        id: 'slot-sl-11',
        slotType: 'accent',
        x: 0.1971,
        y: 0.6945,
        width: 0.0846,
        height: 0.1909,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Lower Left Anchor (A5)',
      },
    ],
    category: 'gallery',
  },
  {
    id: 'vertical-tower-21',
    slug: 'vertical-tower',
    name: '21 — Vertical Tower',
    description:
      'Engineered for tall narrow walls, architectural columns, entryway alcoves, and stairwell landings.',
    badge: 'Narrow Wall Solution',
    wallWidthMm: 850,
    wallHeightMm: 1650,
    coverageLabel: '85 × 165 cm',
    physicalPrintCount: 4,
    logicalArtworkCount: 4,
    recommendedRoom: 'Stairwell / Pillar / Narrow Hallway / Entryway',
    recommendedWallWidth: '1.0 – 1.4 m',
    recommendedThemes: ['Quotes', 'Minimal', 'Architecture', 'Anime', 'Motorsport'],
    basePrice: 599,
    compareAtPrice: 799,
    published: true,
    version: 1,
    sortOrder: 25,
    splitGroups: [],
    slots: [
      {
        id: 'slot-vt-1',
        slotType: 'support',
        x: 0.3765,
        y: 0.0364,
        width: 0.2471,
        height: 0.18,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Tower Crest (A4)',
      },
      {
        id: 'slot-vt-2',
        slotType: 'hero',
        x: 0.3253,
        y: 0.2315,
        width: 0.3494,
        height: 0.2545,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Tower Core Hero (A3)',
      },
      {
        id: 'slot-vt-3',
        slotType: 'support',
        x: 0.3765,
        y: 0.5012,
        width: 0.2471,
        height: 0.18,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Tower Anchor (A4)',
      },
      {
        id: 'slot-vt-4',
        slotType: 'accent',
        x: 0.4129,
        y: 0.6964,
        width: 0.1741,
        height: 0.1273,
        size: 'A5',
        physicalWidthMm: 148,
        physicalHeightMm: 210,
        orientation: 'portrait',
        label: 'Tower Foot Accent (A5)',
      },
    ],
    category: 'gallery',
  },
  {
    id: 'quad-accent-22',
    slug: 'quad-accent',
    name: '22 — Quad Accent',
    description:
      'A dominant A3 centerpiece anchored by 4 diagonal satellite prints in the corners. Balanced, focused, and immediately striking.',
    badge: 'Balanced Radial',
    wallWidthMm: 1450,
    wallHeightMm: 1000,
    coverageLabel: '145 × 100 cm',
    physicalPrintCount: 5,
    logicalArtworkCount: 5,
    recommendedRoom: 'Bedroom / Office / Studio',
    recommendedWallWidth: '1.8 – 2.4 m',
    recommendedThemes: ['Marvel', 'DC', 'Gaming', 'Cars', 'Aesthetic'],
    basePrice: 699,
    compareAtPrice: 899,
    published: true,
    version: 1,
    sortOrder: 26,
    splitGroups: [],
    slots: [
      {
        id: 'slot-qa-hero',
        slotType: 'hero',
        x: 0.3976,
        y: 0.29,
        width: 0.2048,
        height: 0.42,
        size: 'A3',
        physicalWidthMm: 297,
        physicalHeightMm: 420,
        orientation: 'portrait',
        required: true,
        label: 'Center Stage Hero (A3)',
      },
      {
        id: 'slot-qa-tl',
        slotType: 'support',
        x: 0.2355,
        y: 0.145,
        width: 0.1448,
        height: 0.297,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Top-Left Corner (A4)',
      },
      {
        id: 'slot-qa-tr',
        slotType: 'support',
        x: 0.6197,
        y: 0.145,
        width: 0.1448,
        height: 0.297,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Top-Right Corner (A4)',
      },
      {
        id: 'slot-qa-bl',
        slotType: 'support',
        x: 0.2355,
        y: 0.558,
        width: 0.1448,
        height: 0.297,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Bottom-Left Corner (A4)',
      },
      {
        id: 'slot-qa-br',
        slotType: 'support',
        x: 0.6197,
        y: 0.558,
        width: 0.1448,
        height: 0.297,
        size: 'A4',
        physicalWidthMm: 210,
        physicalHeightMm: 297,
        orientation: 'portrait',
        label: 'Bottom-Right Corner (A4)',
      },
    ],
    category: 'gallery',
  },
];

export function getLayoutById(idOrSlug: string): WallLayoutData | undefined {
  if (!idOrSlug) return undefined;
  const normalized = idOrSlug.trim();

  // Direct match
  const exact = FREGORO_LAYOUTS.find((l) => l.id === normalized || l.slug === normalized);
  if (exact) return exact;

  // Intelligent legacy aliases redirecting to enhanced hybrid or split layouts
  if (normalized === 'stepped-hero-05' || normalized === 'stepped-hero') {
    return FREGORO_LAYOUTS.find((l) => l.id === 'hybrid-stepped-triptych-flank-5') || exact;
  }
  if (normalized === 'stepped-grand-06') {
    return FREGORO_LAYOUTS.find((l) => l.id === 'hybrid-stepped-wave-flank-9') || exact;
  }
  if (normalized === 'cinema-07' || normalized === 'cinema') {
    return FREGORO_LAYOUTS.find((l) => l.id === 'hybrid-classic4-cinema-8') || exact;
  }
  if (normalized === 'panorama-08' || normalized === 'panorama') {
    return FREGORO_LAYOUTS.find((l) => l.id === 'hybrid-classic5-grand-panorama-9') || exact;
  }
  if (normalized === 'large-hero-04' || normalized === 'large-hero') {
    return FREGORO_LAYOUTS.find((l) => l.id === 'hybrid-stepped-wave-heritage-11') || exact;
  }

  return undefined;
}
