import type { WallThemeData } from './types';

/**
 * 26 CURATED FREGORO WALL THEMES
 *
 * Scalable theme taxonomy. Adding a theme here or in DB requires zero frontend layout changes.
 */

export const FREGORO_THEMES: WallThemeData[] = [
  {
    id: 'theme-marvel',
    slug: 'marvel',
    name: 'Marvel',
    tagline: 'Earth’s mightiest cinematic art.',
    description: 'Iconic heroes, dark comic editions, and cinematic multiverse captures.',
    accentColor: '#E62429',
    gradient: 'linear-gradient(135deg, #1C0A0A 0%, #E62429 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 1,
  },
  {
    id: 'theme-dc',
    slug: 'dc',
    name: 'DC',
    tagline: 'Shadows, titans & Gotham noir.',
    description: 'Dark knight silhouettes, high-contrast comic ink, and Gotham architectural art.',
    accentColor: '#0047BA',
    gradient: 'linear-gradient(135deg, #050A14 0%, #0047BA 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 2,
  },
  {
    id: 'theme-gaming',
    slug: 'gaming',
    name: 'Gaming',
    tagline: 'Immersive worlds & cybernetic aesthetics.',
    description: 'Cinematic game landscapes, concept art, weapon designs, and glitch typography.',
    accentColor: '#00FF66',
    gradient: 'linear-gradient(135deg, #09140C 0%, #00FF66 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 3,
  },
  {
    id: 'theme-cars',
    slug: 'cars',
    name: 'Cars',
    tagline: 'Pure automotive sculpture.',
    description:
      'Supercar aerodynamics, studio profile renders, tachometer art, and track machines.',
    accentColor: '#E10600',
    gradient: 'linear-gradient(135deg, #1A0D0D 0%, #E10600 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 4,
  },
  {
    id: 'theme-f1',
    slug: 'f1',
    name: 'Formula 1',
    tagline: 'Velocity, telemetry & podiums.',
    description: 'Curva Grande apex captures, Monaco rain sweeps, and driver helmet livery.',
    accentColor: '#FF1801',
    gradient: 'linear-gradient(135deg, #140505 0%, #FF1801 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 5,
  },
  {
    id: 'theme-anime',
    slug: 'anime',
    name: 'Anime',
    tagline: 'Shonen fury & Tokyo nocturnal aesthetics.',
    description: 'Katana choreography, stylized manga ink, and evocative cyberpunk Tokyo skies.',
    accentColor: '#FF3366',
    gradient: 'linear-gradient(135deg, #1C0A14 0%, #FF3366 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 6,
  },
  {
    id: 'theme-kollywood',
    slug: 'kollywood',
    name: 'Kollywood',
    tagline: 'Mass cinema & heroic silhouettes.',
    description: 'Cinematic heroic moments, stylized vintage film titles, and legendary stars.',
    accentColor: '#FFA500',
    gradient: 'linear-gradient(135deg, #1A1205 0%, #FFA500 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 7,
  },
  {
    id: 'theme-football',
    slug: 'football',
    name: 'Football',
    tagline: 'The beautiful game under stadium lights.',
    description: 'Overhead scissor kicks, flooded stadium floodlights, and minimal legend numbers.',
    accentColor: '#00C853',
    gradient: 'linear-gradient(135deg, #051408 0%, #00C853 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 8,
  },
  {
    id: 'theme-cricket',
    slug: 'cricket',
    name: 'Cricket',
    tagline: 'Cover drives & roaring stadiums.',
    description: 'Classic willow strikes, roaring stands, and timeless captaincy moments.',
    accentColor: '#1E88E5',
    gradient: 'linear-gradient(135deg, #08111A 0%, #1E88E5 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 9,
  },
  {
    id: 'theme-music',
    slug: 'music',
    name: 'Music',
    tagline: 'Vinyl, stage smoke & sonic legends.',
    description: 'Live stadium concerts, analog synth waveform art, and vinyl groove photography.',
    accentColor: '#9C27B0',
    gradient: 'linear-gradient(135deg, #140717 0%, #9C27B0 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 10,
  },
  {
    id: 'theme-kpop',
    slug: 'k-pop',
    name: 'K-Pop',
    tagline: 'Pastel neon & concert choreography.',
    description: 'Concert lightsticks, modern typography, and pastel aesthetic stage moments.',
    accentColor: '#E040FB',
    gradient: 'linear-gradient(135deg, #1A081C 0%, #E040FB 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 11,
  },
  {
    id: 'theme-movies',
    slug: 'movies',
    name: 'Movies',
    tagline: 'Classic celluloid & auteur frames.',
    description: 'Iconic film moments, cinematic letterboxing, and timeless directorial frames.',
    accentColor: '#D4AF37',
    gradient: 'linear-gradient(135deg, #17140B 0%, #D4AF37 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 12,
  },
  {
    id: 'theme-series',
    slug: 'series',
    name: 'Series',
    tagline: 'Binge-worthy visual sagas.',
    description: 'Prestige TV art, dystopian backdrops, and memorable character quotes.',
    accentColor: '#FF5722',
    gradient: 'linear-gradient(135deg, #1A0D08 0%, #FF5722 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 13,
  },
  {
    id: 'theme-gym',
    slug: 'gym',
    name: 'Gym & Iron',
    tagline: 'Discipline, chalk & relentless drive.',
    description: 'Chalked barbells, monochrome athlete muscle studies, and stoic discipline art.',
    accentColor: '#78909C',
    gradient: 'linear-gradient(135deg, #101416 0%, #78909C 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 14,
  },
  {
    id: 'theme-quotes',
    slug: 'quotes',
    name: 'Quotes',
    tagline: 'Swiss typography & philosophy.',
    description: 'Minimal editorial text, stoic maxims, and stark black-on-ivory statements.',
    accentColor: '#F5F5F7',
    gradient: 'linear-gradient(135deg, #1A1A1A 0%, #888888 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 15,
  },
  {
    id: 'theme-aesthetic',
    slug: 'aesthetic',
    name: 'Aesthetic',
    tagline: 'Soft sunlight, brutalist concrete & calm.',
    description: 'Modern botanical shadows, brutalist arches, and warm neutral gradient palettes.',
    accentColor: '#D8C3A5',
    gradient: 'linear-gradient(135deg, #1E1A16 0%, #D8C3A5 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 16,
  },
  {
    id: 'theme-retro',
    slug: 'retro',
    name: 'Retro',
    tagline: '70s halftones & 80s synthwaves.',
    description: 'Warm analog grain, vintage advertising layouts, and cassette culture art.',
    accentColor: '#E65100',
    gradient: 'linear-gradient(135deg, #1C0C04 0%, #E65100 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 17,
  },
  {
    id: 'theme-luxury',
    slug: 'luxury',
    name: 'Luxury',
    tagline: 'Haute horlogerie & quiet grandeur.',
    description: 'Chronograph movements, architectural marble, and bespoke minimalist luxury.',
    accentColor: '#C5A059',
    gradient: 'linear-gradient(135deg, #14110A 0%, #C5A059 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 18,
  },
  {
    id: 'theme-photography',
    slug: 'photography',
    name: 'Photography',
    tagline: 'Fine art monochrome & street light.',
    description:
      'High dynamic range black-and-white, foggy streetlamps, and architectural geometry.',
    accentColor: '#B0BEC5',
    gradient: 'linear-gradient(135deg, #121415 0%, #B0BEC5 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 19,
  },
  {
    id: 'theme-technology',
    slug: 'technology',
    name: 'Technology',
    tagline: 'Silicon circuitry & speculative futures.',
    description: 'Macro chip photography, cybernetic diagrams, and generative wireframes.',
    accentColor: '#00E5FF',
    gradient: 'linear-gradient(135deg, #051417 0%, #00E5FF 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 20,
  },
  {
    id: 'theme-street',
    slug: 'street',
    name: 'Street',
    tagline: 'Raw asphalt, graffiti & sneakers.',
    description: 'Tokyo alleys, skateboard culture, stencil art, and urban graffiti textures.',
    accentColor: '#FF6D00',
    gradient: 'linear-gradient(135deg, #190D05 0%, #FF6D00 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 21,
  },
  {
    id: 'theme-motorsport',
    slug: 'motorsport',
    name: 'Motorsport',
    tagline: 'Apex lines, tyre smoke & endurance.',
    description: 'Le Mans 24h dusk laps, classic rally gravel spray, and technical liveries.',
    accentColor: '#FFAB00',
    gradient: 'linear-gradient(135deg, #191305 0%, #FFAB00 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 22,
  },
  {
    id: 'theme-character',
    slug: 'character',
    name: 'Character',
    tagline: 'Villains, antiheroes & mythic faces.',
    description: 'High contrast character close-ups, comic ink portraits, and symbolic masks.',
    accentColor: '#7C4DFF',
    gradient: 'linear-gradient(135deg, #110B22 0%, #7C4DFF 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 23,
  },
  {
    id: 'theme-minimal',
    slug: 'minimal',
    name: 'Minimal',
    tagline: 'Quiet space, perfect proportion.',
    description: 'Bauhaus geometry, single line strokes, and balanced negative space.',
    accentColor: '#FFFFFF',
    gradient: 'linear-gradient(135deg, #111111 0%, #444444 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 24,
  },
  {
    id: 'theme-dark',
    slug: 'dark',
    name: 'Dark & Moody',
    tagline: 'Chiaroscuro, ink & deep shadows.',
    description: 'Black-on-black textures, lunar light, and dramatic chiaroscuro drama.',
    accentColor: '#607D8B',
    gradient: 'linear-gradient(135deg, #0A0D0E 0%, #37474F 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    featured: true,
    sortOrder: 25,
  },
  {
    id: 'theme-pop-culture',
    slug: 'pop-culture',
    name: 'Pop Culture',
    tagline: 'Icons, memes & cultural phenomena.',
    description: 'Bold color blocks, cult references, and modern graphic design statements.',
    accentColor: '#FF4081',
    gradient: 'linear-gradient(135deg, #1C0812 0%, #FF4081 100%)',
    previewImage:
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    featured: false,
    sortOrder: 26,
  },
];

export function getThemeBySlug(slug: string): WallThemeData | undefined {
  return FREGORO_THEMES.find((t) => t.slug === slug || t.id === slug);
}
