export const OFFER_MESSAGES = [
  'FREE SHIPPING OVER ₹999',
  'FLAT 20% OFF YOUR FIRST CUSTOM DESIGN',
  'NEW: SPLIT-PANEL WALL ART',
  'DESIGN IT YOURSELF — UPLOAD ANY PHOTO',
];

export const OFFER_STRING = OFFER_MESSAGES.join(' ✦ ') + ' ✦ ';
