/**
 * Verified Per-Garment UV Panel & Surface Definitions
 * 
 * Anatomical Orientation Convention:
 * - Garment coordinates: Front faces +Z, Back faces -Z, Top/Neck is +Y, Hem/Feet is -Y.
 * - Wearer's perspective:
 *   - Looking at the front from the camera, the wearer looks forward toward +Z.
 *   - Wearer's LEFT arm/side extends toward +X (viewer's right).
 *   - Wearer's RIGHT arm/side extends toward -X (viewer's left).
 * - All axis suffixes (-X, +X) are removed from user-facing labels.
 */

export interface GarmentPanel3D {
  id: string;             // Stable identifier (e.g. 'front_body', 'left_sleeve')
  name: string;           // Clean user-facing display name
  u: number;              // Verified anchor U inside the island (0..1)
  v: number;              // Verified anchor V inside the island (0..1)
  spanU: number;          // Island bounding width on atlas (0..1)
  spanV: number;          // Island bounding height on atlas (0..1)
  minU: number;           // Bounding box min U
  minV: number;           // Bounding box min V
  maxU: number;           // Bounding box max U
  maxV: number;           // Bounding box max V
  color: string;          // Distinct accent color for badge & highlight
  description?: string;
  associatedIslands?: number[];
  printZone?: {
    id: string;
    name: string;
    uvCenter: [number, number];
    uvSpan: [number, number];
  };
}

export const VERIFIED_GARMENT_PANELS: Record<string, GarmentPanel3D[]> = {
  // ── 1. Regular T-Shirt ────────────────────────────────────────────────────
  'regular-t-shirt': [
    {
      id: 'front_body',
      name: 'Front Body',
      u: 0.25,
      v: 0.69,
      spanU: 0.48,
      spanV: 0.58,
      minU: 0.01,
      minV: 0.40,
      maxU: 0.49,
      maxV: 0.98,
      color: '#38bdf8',
      description: 'Front torso panel with crewneck collar scoop',
      printZone: {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.25, 0.65],
        uvSpan: [0.32, 0.32],
      },
    },
    {
      id: 'back_body',
      name: 'Back Body',
      u: 0.75,
      v: 0.69,
      spanU: 0.48,
      spanV: 0.58,
      minU: 0.51,
      minV: 0.40,
      maxU: 0.99,
      maxV: 0.98,
      color: '#a855f7',
      description: 'Full rear torso panel',
      printZone: {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.75, 0.64],
        uvSpan: [0.32, 0.32],
      },
    },
    {
      id: 'left_sleeve',
      name: 'Left Sleeve',
      u: 0.75,
      v: 0.24,
      spanU: 0.40,
      spanV: 0.20,
      minU: 0.55,
      minV: 0.14,
      maxU: 0.95,
      maxV: 0.34,
      color: '#34d399',
      description: 'Wearer left arm sleeve panel (+X)',
    },
    {
      id: 'right_sleeve',
      name: 'Right Sleeve',
      u: 0.21,
      v: 0.24,
      spanU: 0.40,
      spanV: 0.20,
      minU: 0.01,
      minV: 0.14,
      maxU: 0.41,
      maxV: 0.34,
      color: '#f472b6',
      description: 'Wearer right arm sleeve panel (-X)',
    },
    {
      id: 'collar',
      name: 'Collar',
      u: 0.49,
      v: 0.15,
      spanU: 0.30,
      spanV: 0.03,
      minU: 0.34,
      minV: 0.14,
      maxU: 0.64,
      maxV: 0.17,
      color: '#fbbf24',
      description: 'Ribbed crewneck collar trim',
    },
  ],

  // ── 2. Oversized T-Shirt ──────────────────────────────────────────────────
  'oversized-t-shirt': [
    {
      id: 'front_body',
      name: 'Front Body',
      u: 0.75,
      v: 0.70,
      spanU: 0.49,
      spanV: 0.58,
      minU: 0.51,
      minV: 0.41,
      maxU: 0.99,
      maxV: 0.99,
      color: '#38bdf8',
      description: 'Heavyweight oversized front torso panel',
      printZone: {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.75, 0.66],
        uvSpan: [0.34, 0.34],
      },
    },
    {
      id: 'back_body',
      name: 'Back Body',
      u: 0.25,
      v: 0.32,
      spanU: 0.49,
      spanV: 0.58,
      minU: 0.01,
      minV: 0.03,
      maxU: 0.49,
      maxV: 0.61,
      color: '#a855f7',
      description: 'Wide drop-shoulder rear canvas panel',
      printZone: {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.25, 0.28],
        uvSpan: [0.34, 0.34],
      },
    },
    {
      id: 'left_sleeve',
      name: 'Left Sleeve',
      u: 0.19,
      v: 0.74,
      spanU: 0.36,
      spanV: 0.24,
      minU: 0.01,
      minV: 0.62,
      maxU: 0.37,
      maxV: 0.86,
      color: '#34d399',
      description: 'Wearer left drop-shoulder sleeve (+X)',
    },
    {
      id: 'right_sleeve',
      name: 'Right Sleeve',
      u: 0.76,
      v: 0.25,
      spanU: 0.36,
      spanV: 0.24,
      minU: 0.58,
      minV: 0.13,
      maxU: 0.94,
      maxV: 0.37,
      color: '#f472b6',
      description: 'Wearer right drop-shoulder sleeve (-X)',
    },
    {
      id: 'collar',
      name: 'Collar',
      u: 0.20,
      v: 0.96,
      spanU: 0.38,
      spanV: 0.03,
      minU: 0.01,
      minV: 0.95,
      maxU: 0.39,
      maxV: 0.98,
      color: '#fbbf24',
      description: 'Chunky ribbed neckline binding',
    },
  ],

  // ── 3. Fitted T-Shirt ─────────────────────────────────────────────────────
  'fitted-t-shirt': [
    {
      id: 'front_body',
      name: 'Front Body',
      u: 0.26,
      v: 0.63,
      spanU: 0.49,
      spanV: 0.66,
      minU: 0.01,
      minV: 0.30,
      maxU: 0.50,
      maxV: 0.96,
      color: '#38bdf8',
      description: 'Contoured athletic front body panel',
      printZone: {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.26, 0.59],
        uvSpan: [0.30, 0.30],
      },
    },
    {
      id: 'back_body',
      name: 'Back Body',
      u: 0.75,
      v: 0.40,
      spanU: 0.49,
      spanV: 0.68,
      minU: 0.51,
      minV: 0.06,
      maxU: 0.99,
      maxV: 0.74,
      color: '#a855f7',
      description: 'Athletic cut rear body panel',
      printZone: {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.74, 0.35],
        uvSpan: [0.30, 0.30],
      },
    },
    {
      id: 'left_sleeve',
      name: 'Left Sleeve',
      u: 0.72,
      v: 0.86,
      spanU: 0.38,
      spanV: 0.21,
      minU: 0.53,
      minV: 0.75,
      maxU: 0.91,
      maxV: 0.96,
      color: '#34d399',
      description: 'Wearer left tailored arm sleeve (+X)',
    },
    {
      id: 'right_sleeve',
      name: 'Right Sleeve',
      u: 0.23,
      v: 0.18,
      spanU: 0.38,
      spanV: 0.21,
      minU: 0.04,
      minV: 0.07,
      maxU: 0.42,
      maxV: 0.28,
      color: '#f472b6',
      description: 'Wearer right tailored arm sleeve (-X)',
    },
    {
      id: 'collar',
      name: 'Collar',
      u: 0.23,
      v: 0.02,
      spanU: 0.42,
      spanV: 0.03,
      minU: 0.02,
      minV: 0.01,
      maxU: 0.44,
      maxV: 0.04,
      color: '#fbbf24',
      description: 'Fitted ribbed neckline trim',
    },
  ],

  // ── 4. Pullover Hoodie ────────────────────────────────────────────────────
  'hoodie': [
    {
      id: 'front_body',
      name: 'Front Body',
      u: 0.21,
      v: 0.39,
      spanU: 0.39,
      spanV: 0.40,
      minU: 0.01,
      minV: 0.19,
      maxU: 0.40,
      maxV: 0.59,
      color: '#38bdf8',
      description: 'Front fleece torso above pocket',
      printZone: {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.21, 0.38],
        uvSpan: [0.28, 0.28],
      },
    },
    {
      id: 'back_body',
      name: 'Back Body',
      u: 0.21,
      v: 0.79,
      spanU: 0.39,
      spanV: 0.39,
      minU: 0.01,
      minV: 0.59,
      maxU: 0.40,
      maxV: 0.99,
      color: '#a855f7',
      description: 'Full rear hoodie panel',
      printZone: {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.21, 0.78],
        uvSpan: [0.30, 0.30],
      },
    },
    {
      id: 'left_sleeve',
      name: 'Left Sleeve',
      u: 0.55,
      v: 0.82,
      spanU: 0.31,
      spanV: 0.34,
      minU: 0.39,
      minV: 0.65,
      maxU: 0.71,
      maxV: 0.99,
      color: '#34d399',
      description: 'Wearer left fleece sleeve (+X)',
    },
    {
      id: 'right_sleeve',
      name: 'Right Sleeve',
      u: 0.55,
      v: 0.47,
      spanU: 0.31,
      spanV: 0.34,
      minU: 0.39,
      minV: 0.30,
      maxU: 0.71,
      maxV: 0.64,
      color: '#f472b6',
      description: 'Wearer right fleece sleeve (-X)',
    },
    {
      id: 'hood',
      name: 'Hood',
      u: 0.81,
      v: 0.74,
      spanU: 0.35,
      spanV: 0.52,
      minU: 0.70,
      minV: 0.48,
      maxU: 0.95,
      maxV: 0.99,
      color: '#ec4899',
      description: 'Dual-layer fleece hood panels',
    },
    {
      id: 'pocket',
      name: 'Kangaroo Pocket',
      u: 0.55,
      v: 0.20,
      spanU: 0.22,
      spanV: 0.14,
      minU: 0.44,
      minV: 0.13,
      maxU: 0.66,
      maxV: 0.27,
      color: '#f97316',
      description: 'Centered pouch pocket panel',
    },
    {
      id: 'waistband',
      name: 'Waistband',
      u: 0.21,
      v: 0.12,
      spanU: 0.32,
      spanV: 0.05,
      minU: 0.05,
      minV: 0.10,
      maxU: 0.37,
      maxV: 0.15,
      color: '#10b981',
      description: 'Elastic ribbed bottom hem',
    },
    {
      id: 'cuffs',
      name: 'Cuffs',
      u: 0.20,
      v: 0.03,
      spanU: 0.30,
      spanV: 0.04,
      minU: 0.05,
      minV: 0.01,
      maxU: 0.35,
      maxV: 0.05,
      color: '#3B5EFF',
      description: 'Ribbed wrist cuffs',
    },
  ],

  // ── 5. Zip-Up Hoodie ──────────────────────────────────────────────────────
  'zip-hoodie': [
    {
      id: 'back_body',
      name: 'Back Body',
      u: 0.44,
      v: 0.73,
      spanU: 0.41,
      spanV: 0.42,
      minU: 0.24,
      minV: 0.52,
      maxU: 0.65,
      maxV: 0.94,
      color: '#a855f7',
      description: 'Continuous back fleece panel',
      printZone: {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.44, 0.72],
        uvSpan: [0.35, 0.35],
      },
    },
    {
      id: 'front_left',
      name: 'Front Left Body',
      u: 0.82,
      v: 0.22,
      spanU: 0.20,
      spanV: 0.42,
      minU: 0.72,
      minV: 0.01,
      maxU: 0.92,
      maxV: 0.43,
      color: '#38bdf8',
      description: 'Wearer left chest panel (+X)',
      printZone: {
        id: 'front-left',
        name: 'Left Chest',
        uvCenter: [0.82, 0.22],
        uvSpan: [0.18, 0.26],
      },
    },
    {
      id: 'front_right',
      name: 'Front Right Body',
      u: 0.12,
      v: 0.73,
      spanU: 0.20,
      spanV: 0.41,
      minU: 0.02,
      minV: 0.52,
      maxU: 0.22,
      maxV: 0.94,
      color: '#06b6d4',
      description: 'Wearer right chest panel (-X)',
      printZone: {
        id: 'front-right',
        name: 'Right Chest',
        uvCenter: [0.12, 0.73],
        uvSpan: [0.18, 0.26],
      },
    },
    {
      id: 'left_sleeve',
      name: 'Left Sleeve',
      u: 0.24,
      v: 0.29,
      spanU: 0.31,
      spanV: 0.35,
      minU: 0.08,
      minV: 0.11,
      maxU: 0.40,
      maxV: 0.46,
      color: '#34d399',
      description: 'Wearer left arm sleeve (+X)',
    },
    {
      id: 'right_sleeve',
      name: 'Right Sleeve',
      u: 0.56,
      v: 0.29,
      spanU: 0.31,
      spanV: 0.35,
      minU: 0.41,
      minV: 0.11,
      maxU: 0.72,
      maxV: 0.46,
      color: '#f472b6',
      description: 'Wearer right arm sleeve (-X)',
    },
    {
      id: 'hood',
      name: 'Hood',
      u: 0.78,
      v: 0.70,
      spanU: 0.25,
      spanV: 0.52,
      minU: 0.68,
      minV: 0.44,
      maxU: 0.90,
      maxV: 0.95,
      color: '#ec4899',
      description: 'Split hoodie hood panels',
    },
    {
      id: 'left_pocket',
      name: 'Left Pocket',
      u: 0.08,
      v: 0.07,
      spanU: 0.13,
      spanV: 0.13,
      minU: 0.01,
      minV: 0.01,
      maxU: 0.14,
      maxV: 0.14,
      color: '#f97316',
      description: 'Wearer left split front pocket (+X)',
    },
    {
      id: 'right_pocket',
      name: 'Right Pocket',
      u: 0.92,
      v: 0.82,
      spanU: 0.13,
      spanV: 0.13,
      minU: 0.86,
      minV: 0.76,
      maxU: 0.99,
      maxV: 0.89,
      color: '#fb923c',
      description: 'Wearer right split front pocket (-X)',
    },
    {
      id: 'waistband',
      name: 'Waistband',
      u: 0.34,
      v: 0.97,
      spanU: 0.62,
      spanV: 0.05,
      minU: 0.03,
      minV: 0.95,
      maxU: 0.65,
      maxV: 0.99,
      color: '#10b981',
      description: 'Bottom hem ribbing',
    },
    {
      id: 'cuffs',
      name: 'Cuffs',
      u: 0.64,
      v: 0.74,
      spanU: 0.35,
      spanV: 0.50,
      minU: 0.44,
      minV: 0.49,
      maxU: 0.84,
      maxV: 0.99,
      color: '#3B5EFF',
      description: 'Wrist cuff ribbing',
    },
  ],

  // ── 6. Crewneck Sweatshirt ────────────────────────────────────────────────
  'sweatshirt': [
    {
      id: 'front_body',
      name: 'Front Body',
      u: 0.24,
      v: 0.25,
      spanU: 0.46,
      spanV: 0.48,
      minU: 0.01,
      minV: 0.01,
      maxU: 0.47,
      maxV: 0.49,
      color: '#38bdf8',
      description: 'Raglan cut fleece front body',
      printZone: {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.24, 0.25],
        uvSpan: [0.30, 0.30],
      },
    },
    {
      id: 'back_body',
      name: 'Back Body',
      u: 0.24,
      v: 0.75,
      spanU: 0.46,
      spanV: 0.48,
      minU: 0.01,
      minV: 0.51,
      maxU: 0.47,
      maxV: 0.99,
      color: '#a855f7',
      description: 'Raglan cut fleece back body',
      printZone: {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.24, 0.75],
        uvSpan: [0.30, 0.30],
      },
    },
    {
      id: 'left_sleeve',
      name: 'Left Sleeve',
      u: 0.67,
      v: 0.68,
      spanU: 0.37,
      spanV: 0.41,
      minU: 0.49,
      minV: 0.48,
      maxU: 0.86,
      maxV: 0.89,
      color: '#34d399',
      description: 'Wearer left raglan sleeve (+X)',
    },
    {
      id: 'right_sleeve',
      name: 'Right Sleeve',
      u: 0.70,
      v: 0.25,
      spanU: 0.37,
      spanV: 0.41,
      minU: 0.52,
      minV: 0.04,
      maxU: 0.89,
      maxV: 0.45,
      color: '#f472b6',
      description: 'Wearer right raglan sleeve (-X)',
    },
    {
      id: 'waistband',
      name: 'Waistband',
      u: 0.91,
      v: 0.61,
      spanU: 0.05,
      spanV: 0.76,
      minU: 0.89,
      minV: 0.23,
      maxU: 0.93,
      maxV: 0.99,
      color: '#10b981',
      description: 'Heavyweight bottom ribbing',
    },
    {
      id: 'collar',
      name: 'Collar',
      u: 0.85,
      v: 0.81,
      spanU: 0.03,
      spanV: 0.37,
      minU: 0.84,
      minV: 0.62,
      maxU: 0.86,
      maxV: 0.99,
      color: '#fbbf24',
      description: 'Crewneck ribbed collar',
    },
    {
      id: 'cuffs',
      name: 'Cuffs',
      u: 0.51,
      v: 0.65,
      spanU: 0.15,
      spanV: 0.65,
      minU: 0.47,
      minV: 0.30,
      maxU: 0.55,
      maxV: 0.99,
      color: '#3B5EFF',
      description: 'Ribbed sleeve cuffs',
    },
  ],

  // ── 7. Sweatpants ─────────────────────────────────────────────────────────
  'sweatpants': [
    {
      id: 'front_left_leg',
      name: 'Front Left Leg',
      u: 0.31,
      v: 0.63,
      spanU: 0.16,
      spanV: 0.61,
      minU: 0.23,
      minV: 0.32,
      maxU: 0.39,
      maxV: 0.93,
      color: '#38bdf8',
      description: 'Front wearer left thigh & leg (+X)',
      printZone: {
        id: 'left-leg',
        name: 'Left Thigh',
        uvCenter: [0.31, 0.55],
        uvSpan: [0.16, 0.32],
      },
    },
    {
      id: 'front_right_leg',
      name: 'Front Right Leg',
      u: 0.09,
      v: 0.64,
      spanU: 0.16,
      spanV: 0.61,
      minU: 0.01,
      minV: 0.33,
      maxU: 0.17,
      maxV: 0.94,
      color: '#06b6d4',
      description: 'Front wearer right thigh & leg (-X)',
      printZone: {
        id: 'right-leg',
        name: 'Right Thigh',
        uvCenter: [0.09, 0.55],
        uvSpan: [0.16, 0.32],
      },
    },
    {
      id: 'back_left_leg',
      name: 'Back Left Leg',
      u: 0.57,
      v: 0.68,
      spanU: 0.20,
      spanV: 0.62,
      minU: 0.47,
      minV: 0.37,
      maxU: 0.67,
      maxV: 0.99,
      color: '#a855f7',
      description: 'Rear wearer left leg (+X)',
    },
    {
      id: 'back_right_leg',
      name: 'Back Right Leg',
      u: 0.81,
      v: 0.68,
      spanU: 0.20,
      spanV: 0.62,
      minU: 0.71,
      minV: 0.37,
      maxU: 0.91,
      maxV: 0.99,
      color: '#c084fc',
      description: 'Rear wearer right leg (-X)',
    },
    {
      id: 'waistband',
      name: 'Waistband',
      u: 0.33,
      v: 0.18,
      spanU: 0.55,
      spanV: 0.03,
      minU: 0.06,
      minV: 0.16,
      maxU: 0.61,
      maxV: 0.19,
      color: '#10b981',
      description: 'Elastic waistband with drawstring portal',
    },
    {
      id: 'back_pocket',
      name: 'Back Pocket',
      u: 0.86,
      v: 0.28,
      spanU: 0.07,
      spanV: 0.08,
      minU: 0.82,
      minV: 0.24,
      maxU: 0.89,
      maxV: 0.32,
      color: '#f97316',
      description: 'Single rear patch pocket',
    },
  ],

  // ── 8. Denim Jeans ────────────────────────────────────────────────────────
  'jeans': [
    {
      id: 'front_left_leg',
      name: 'Front Left Leg',
      u: 0.34,
      v: 0.66,
      spanU: 0.20,
      spanV: 0.66,
      minU: 0.24,
      minV: 0.33,
      maxU: 0.44,
      maxV: 0.99,
      color: '#38bdf8',
      description: 'Front wearer left denim leg panel (+X)',
      printZone: {
        id: 'front-leg',
        name: 'Front Leg',
        uvCenter: [0.34, 0.66],
        uvSpan: [0.20, 0.32],
      },
    },
    {
      id: 'front_right_leg',
      name: 'Front Right Leg',
      u: 0.89,
      v: 0.42,
      spanU: 0.20,
      spanV: 0.66,
      minU: 0.79,
      minV: 0.08,
      maxU: 0.99,
      maxV: 0.75,
      color: '#06b6d4',
      description: 'Front wearer right denim leg panel (-X)',
    },
    {
      id: 'back_left_leg',
      name: 'Back Left Leg',
      u: 0.14,
      v: 0.42,
      spanU: 0.26,
      spanV: 0.66,
      minU: 0.01,
      minV: 0.08,
      maxU: 0.27,
      maxV: 0.75,
      color: '#a855f7',
      description: 'Rear wearer left denim leg panel (+X)',
    },
    {
      id: 'back_right_leg',
      name: 'Back Right Leg',
      u: 0.60,
      v: 0.54,
      spanU: 0.35,
      spanV: 0.91,
      minU: 0.42,
      minV: 0.08,
      maxU: 0.77,
      maxV: 0.99,
      color: '#c084fc',
      description: 'Rear wearer right denim leg panel (-X)',
    },
    {
      id: 'back_pockets',
      name: 'Back Pockets',
      u: 0.48,
      v: 0.14,
      spanU: 0.35,
      spanV: 0.12,
      minU: 0.19,
      minV: 0.08,
      maxU: 0.53,
      maxV: 0.19,
      color: '#f97316',
      description: 'Traditional five-pocket rear pockets',
      printZone: {
        id: 'back-pocket',
        name: 'Back Pocket',
        uvCenter: [0.48, 0.14],
        uvSpan: [0.12, 0.12],
      },
    },
    {
      id: 'front_pockets',
      name: 'Front Pockets',
      u: 0.36,
      v: 0.15,
      spanU: 0.20,
      spanV: 0.15,
      minU: 0.02,
      minV: 0.08,
      maxU: 0.41,
      maxV: 0.22,
      color: '#eab308',
      description: 'Front scoop pockets & coin pocket',
    },
    {
      id: 'waistband',
      name: 'Waistband',
      u: 0.77,
      v: 0.69,
      spanU: 0.05,
      spanV: 0.35,
      minU: 0.75,
      minV: 0.54,
      maxU: 0.80,
      maxV: 0.90,
      color: '#10b981',
      description: 'Stitched denim waistband with belt loops',
    },
  ],

  // ── 9. Tank Top ───────────────────────────────────────────────────────────
  'tank-top': [
    {
      id: 'front_body',
      name: 'Front Body',
      u: 0.26,
      v: 0.64,
      spanU: 0.47,
      spanV: 0.69,
      minU: 0.03,
      minV: 0.30,
      maxU: 0.50,
      maxV: 0.99,
      color: '#38bdf8',
      description: 'Sleeveless deep scoop front torso',
      printZone: {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.26, 0.64],
        uvSpan: [0.28, 0.32],
      },
    },
    {
      id: 'back_body',
      name: 'Back Body',
      u: 0.74,
      v: 0.65,
      spanU: 0.47,
      spanV: 0.69,
      minU: 0.51,
      minV: 0.30,
      maxU: 0.98,
      maxV: 0.99,
      color: '#a855f7',
      description: 'Racerback rear torso panel',
      printZone: {
        id: 'back',
        name: 'Racerback',
        uvCenter: [0.74, 0.65],
        uvSpan: [0.28, 0.32],
      },
    },
    {
      id: 'left_armhole',
      name: 'Left Armhole Trim',
      u: 0.99,
      v: 0.69,
      spanU: 0.02,
      spanV: 0.56,
      minU: 0.98,
      minV: 0.41,
      maxU: 1.00,
      maxV: 0.97,
      color: '#34d399',
      description: 'Wearer left armhole binding (+X)',
    },
    {
      id: 'right_armhole',
      name: 'Right Armhole Trim',
      u: 0.01,
      v: 0.70,
      spanU: 0.02,
      spanV: 0.56,
      minU: 0.00,
      minV: 0.42,
      maxU: 0.02,
      maxV: 0.98,
      color: '#f472b6',
      description: 'Wearer right armhole binding (-X)',
    },
    {
      id: 'neck_trim',
      name: 'Neck Trim',
      u: 0.46,
      v: 0.21,
      spanU: 0.54,
      spanV: 0.02,
      minU: 0.19,
      minV: 0.20,
      maxU: 0.73,
      maxV: 0.22,
      color: '#fbbf24',
      description: 'Reinforced scoop neck binding',
    },
  ],

  // ── 10. Baseball Cap ──────────────────────────────────────────────────────
  'cap': [
    {
      id: 'front_crown',
      name: 'Front Crown',
      u: 0.33,
      v: 0.75,
      spanU: 0.36,
      spanV: 0.34,
      minU: 0.15,
      minV: 0.58,
      maxU: 0.51,
      maxV: 0.92,
      color: '#38bdf8',
      description: 'Structured 2-panel front forehead section',
      printZone: {
        id: 'crown',
        name: 'Front Crown',
        uvCenter: [0.33, 0.75],
        uvSpan: [0.28, 0.28],
      },
    },
    {
      id: 'visor_brim',
      name: 'Visor / Brim',
      u: 0.25,
      v: 0.20,
      spanU: 0.47,
      spanV: 0.38,
      minU: 0.01,
      minV: 0.01,
      maxU: 0.48,
      maxV: 0.39,
      color: '#34d399',
      description: 'Curved visor top surface',
    },
    {
      id: 'side_panels',
      name: 'Side Panels',
      u: 0.50,
      v: 0.50,
      spanU: 0.36,
      spanV: 0.30,
      minU: 0.32,
      minV: 0.35,
      maxU: 0.68,
      maxV: 0.65,
      color: '#f59e0b',
      description: 'Left and right crown side panels',
    },
    {
      id: 'back_panels',
      name: 'Back Panels',
      u: 0.74,
      v: 0.79,
      spanU: 0.45,
      spanV: 0.32,
      minU: 0.51,
      minV: 0.64,
      maxU: 0.96,
      maxV: 0.96,
      color: '#a855f7',
      description: 'Rear arch and strap closure panels',
      printZone: {
        id: 'back',
        name: 'Back Arch',
        uvCenter: [0.74, 0.79],
        uvSpan: [0.25, 0.25],
      },
    },
    {
      id: 'sweatband',
      name: 'Sweatband',
      u: 0.98,
      v: 0.34,
      spanU: 0.05,
      spanV: 0.70,
      minU: 0.95,
      minV: 0.00,
      maxU: 1.00,
      maxV: 0.70,
      color: '#10b981',
      description: 'Interior moisture-wicking sweatband',
    },
  ],

  // ── 11. Balaclava ─────────────────────────────────────────────────────────
  'balaclava': [
    {
      id: 'left_head',
      name: 'Left Face & Head',
      u: 0.20,
      v: 0.32,
      spanU: 0.38,
      spanV: 0.61,
      minU: 0.01,
      minV: 0.01,
      maxU: 0.39,
      maxV: 0.62,
      color: '#38bdf8',
      description: 'Wearer left thermal head & cheek profile (+X)',
      printZone: {
        id: 'forehead',
        name: 'Left Face',
        uvCenter: [0.20, 0.32],
        uvSpan: [0.25, 0.25],
      },
    },
    {
      id: 'right_head',
      name: 'Right Face & Head',
      u: 0.60,
      v: 0.32,
      spanU: 0.38,
      spanV: 0.61,
      minU: 0.41,
      minV: 0.01,
      maxU: 0.79,
      maxV: 0.62,
      color: '#06b6d4',
      description: 'Wearer right thermal head & cheek profile (-X)',
      printZone: {
        id: 'back',
        name: 'Right Head',
        uvCenter: [0.60, 0.32],
        uvSpan: [0.25, 0.25],
      },
    },
    {
      id: 'left_neck',
      name: 'Left Neck',
      u: 0.20,
      v: 0.71,
      spanU: 0.38,
      spanV: 0.13,
      minU: 0.01,
      minV: 0.64,
      maxU: 0.39,
      maxV: 0.77,
      color: '#34d399',
      description: 'Wearer left lower neck collar (+X)',
    },
    {
      id: 'right_neck',
      name: 'Right Neck',
      u: 0.20,
      v: 0.90,
      spanU: 0.38,
      spanV: 0.13,
      minU: 0.01,
      minV: 0.83,
      maxU: 0.39,
      maxV: 0.96,
      color: '#f472b6',
      description: 'Wearer right lower neck collar (-X)',
    },
    {
      id: 'eye_trim',
      name: 'Eye Portal Trim',
      u: 0.46,
      v: 0.80,
      spanU: 0.49,
      spanV: 0.02,
      minU: 0.22,
      minV: 0.79,
      maxU: 0.71,
      maxV: 0.82,
      color: '#fbbf24',
      description: 'Reinforced eye opening portal binding',
    },
  ],
};

/**
 * Retrieve verified physical panels for a specific garment ID.
 */
export function getGarmentPanels(garmentId: string): GarmentPanel3D[] {
  return VERIFIED_GARMENT_PANELS[garmentId] || VERIFIED_GARMENT_PANELS['regular-t-shirt'];
}

/**
 * Locate which garment panel contains a given UV coordinate.
 */
export function findPanelAtUV(garmentId: string, u: number, v: number): GarmentPanel3D | null {
  const panels = getGarmentPanels(garmentId);
  // First, check bounding box containment
  for (const panel of panels) {
    if (u >= panel.minU && u <= panel.maxU && v >= panel.minV && v <= panel.maxV) {
      return panel;
    }
  }
  // Fallback: closest anchor distance within 0.15 radius
  let closest: GarmentPanel3D | null = null;
  let minDist = 0.15;
  for (const panel of panels) {
    const d = Math.hypot(u - panel.u, v - panel.v);
    if (d < minDist) {
      minDist = d;
      closest = panel;
    }
  }
  return closest;
}

/**
 * Locate a garment panel by its ID.
 */
export function findPanelById(garmentId: string, panelId: string): GarmentPanel3D | null {
  const panels = getGarmentPanels(garmentId);
  return panels.find((p) => p.id === panelId) || null;
}

