import type { Garment3DConfig } from '../../types/threeD';

export const GARMENT_3D_CATALOG: Garment3DConfig[] = [
  {
    id: 'regular-t-shirt',
    name: 'Regular T-Shirt',
    category: 't-shirts',
    modelFilename: 'Regular_T-Shirt.glb',
    modelPath: '/3d-assets/GLB/Regular_T-Shirt.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/regular-t-shirt.jpg',
    garmentNodeName: 'Stick',
    neckTagNodeName: 'NeckTag',
    positionNodeName: 'ModelPosition',
    masterClipName: 'WALK',
    textures: {
      diffuse: '/3d-assets/t-shirt_diffuse.jpg',
      normal: '/3d-assets/t-shirt_normal.jpg',
      roughness: '/3d-assets/t-shirt_roughness.jpg',
    },
    regions: [
      {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.25, 0.65],
        uvSpan: [0.32, 0.32],
        description: 'Centered on front chest',
      },
      {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.75, 0.64],
        uvSpan: [0.32, 0.32],
        description: 'Centered on upper back',
      },
    ],
    cameraDefaults: {
      target: [0, 0, 0],
      distance: 7.5,
      fov: 45,
    },
    wiggleBoneNames: ['Bone1', 'Bone2', 'Bone3', 'Bone4', 'Bone5', 'Bone6', 'Bone7', 'Bone8'],
    description: 'Classic unisex crewneck t-shirt with natural cotton drape.',
  },
  {
    id: 'oversized-t-shirt',
    name: 'Oversized T-Shirt',
    category: 't-shirts',
    modelFilename: 'Oversized_T-Shirt.glb',
    modelPath: '/3d-assets/GLB/Oversized_T-Shirt.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/Oversized_t-shirt.jpg',
    garmentNodeName: 'Oversized_T-Shirt',
    neckTagNodeName: 'NeckTag_Oversized_T-Shirt',
    positionNodeName: 'ModelPosition_Oversized_T-Shirt',
    masterClipName: 'WALK_Oversized_T-Shirt',
    textures: {
      diffuse: '/3d-assets/Oversized_T-Shirt_diffuse.jpg',
      normal: '/3d-assets/Oversized_T-Shirt_normal.jpg',
      roughness: '/3d-assets/Oversized_T-Shirt_diffuse.jpg',
    },
    regions: [
      {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.75, 0.66],
        uvSpan: [0.34, 0.34],
        description: 'Drop-shoulder chest print',
      },
      {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.25, 0.28],
        uvSpan: [0.34, 0.34],
        description: 'Oversized back canvas',
      },
    ],
    cameraDefaults: {
      target: [0, 0, 0],
      distance: 8.0,
      fov: 45,
    },
    wiggleBoneNames: ['Oversized_T-Shirt_Bone1', 'Oversized_T-Shirt_Bone2', 'Oversized_T-Shirt_Bone3', 'Oversized_T-Shirt_Bone4'],
    description: 'Heavyweight boxy cut with relaxed dropped shoulders.',
  },
  {
    id: 'fitted-t-shirt',
    name: 'Fitted T-Shirt',
    category: 't-shirts',
    modelFilename: 'Fitted_T-Shirt.glb',
    modelPath: '/3d-assets/GLB/Fitted_T-Shirt.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/Fitted_t-shirt.jpg',
    garmentNodeName: 'Fitted_T-Shirt',
    neckTagNodeName: 'NeckTag_Fitted_T-Shirt',
    positionNodeName: 'ModelPosition_Fitted_T-Shirt',
    masterClipName: 'WALK_Fitted_T-Shirt',
    textures: {
      diffuse: '/3d-assets/Fitted_t-shirt_diffuse.jpg',
      normal: '/3d-assets/Fitted_t-shirt_normal.jpg',
      roughness: '/3d-assets/Fitted_t-shirt_roughness.jpg',
    },
    regions: [
      {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.26, 0.59],
        uvSpan: [0.30, 0.30],
        description: 'Athletic cut front placement',
      },
      {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.74, 0.35],
        uvSpan: [0.30, 0.30],
        description: 'Upper back placement',
      },
    ],
    cameraDefaults: {
      target: [0, 0, 0],
      distance: 7.5,
      fov: 45,
    },
    wiggleBoneNames: ['Fitted_T-Shirt_Bone1', 'Fitted_T-Shirt_Bone2', 'Fitted_T-Shirt_Bone3', 'Fitted_T-Shirt_Bone4'],
    description: 'Tailored athletic fit contouring the torso and arms.',
  },
  {
    id: 'hoodie',
    name: 'Pullover Hoodie',
    category: 'hoodies',
    modelFilename: 'Hoodie.glb',
    modelPath: '/3d-assets/GLB/Hoodie.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/hoodie.jpg',
    garmentNodeName: 'Hoodie',
    neckTagNodeName: 'NeckTag_Hoodie',
    positionNodeName: 'ModelPosition_Hoodie',
    masterClipName: 'WALK_Hoodie',
    textures: {
      diffuse: '/3d-assets/hoodie_diffuse.jpg',
      normal: '/3d-assets/hoodie_normal.jpg',
      roughness: '/3d-assets/hoodie_roughness.jpg',
    },
    regions: [
      {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.21, 0.38],
        uvSpan: [0.30, 0.30],
        description: 'Centered on front hoodie body',
      },
      {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.21, 0.78],
        uvSpan: [0.30, 0.30],
        description: 'Full back hoodie panel',
      },
    ],
    cameraDefaults: {
      target: [0, 0.2, 0],
      distance: 8.5,
      fov: 45,
    },
    wiggleBoneNames: ['Hoodie_Bone5', 'Hoodie_Bone7', 'Hoodie_Bone8', 'Hoodie_Bone9', 'Hoodie_Bone10'],
    description: 'Heavyweight fleece pullover hoodie with double-layer hood.',
  },
  {
    id: 'zip-hoodie',
    name: 'Zip-Up Hoodie',
    category: 'hoodies',
    modelFilename: 'Zip_Hoodie.glb',
    modelPath: '/3d-assets/GLB/Zip_Hoodie.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/zip-hoodie.jpg',
    garmentNodeName: 'Zip-Hoodie',
    positionNodeName: 'ModelPosition_Zip-Hoodie',
    masterClipName: 'WALK_Zip-Hoodie',
    textures: {
      diffuse: '/3d-assets/Zip-Hoodie_diffuse.jpg',
      normal: '/3d-assets/Zip-Hoodie_normal.jpg',
      roughness: '/3d-assets/sweatpants_roughness.jpg',
    },
    regions: [
      {
        id: 'front-left',
        name: 'Left Chest',
        uvCenter: [0.82, 0.22],
        uvSpan: [0.22, 0.28],
        description: 'Front wearer-left chest area',
      },
      {
        id: 'front-right',
        name: 'Right Chest',
        uvCenter: [0.12, 0.73],
        uvSpan: [0.20, 0.28],
        description: 'Front wearer-right chest area',
      },
      {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.44, 0.72],
        uvSpan: [0.32, 0.35],
        description: 'Continuous back print area',
      },
    ],
    cameraDefaults: {
      target: [0, 0.3, 0],
      distance: 8.5,
      fov: 45,
    },
    wiggleBoneNames: ['Bone1', 'Bone2', 'Bone3', 'Bone4', 'Bone5', 'Bone6', 'Bone7', 'Bone8'],
    description: 'Full-zip fleece jacket with metallic zipper track and split pocket.',
  },
  {
    id: 'sweatshirt',
    name: 'Crewneck Sweatshirt',
    category: 'hoodies',
    modelFilename: 'Sweatshirt.glb',
    modelPath: '/3d-assets/GLB/Sweatshirt.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/sweatshirt.jpg',
    garmentNodeName: 'Sweatshirt',
    neckTagNodeName: 'NeckTag_Sweatshirt',
    positionNodeName: 'ModelPosition_Sweatshirt',
    masterClipName: 'WALK_Sweatshirt',
    textures: {
      diffuse: '/3d-assets/Sweatshirt_diffuse.jpg',
      normal: '/3d-assets/Sweatshirt_normal.jpg',
      roughness: '/3d-assets/Sweatshirt_roughness.jpg',
    },
    regions: [
      {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.25, 0.24],
        uvSpan: [0.30, 0.30],
        description: 'Centered on ribbed crewneck',
      },
      {
        id: 'back',
        name: 'Back Center',
        uvCenter: [0.24, 0.73],
        uvSpan: [0.30, 0.30],
        description: 'Spacious upper back area',
      },
    ],
    cameraDefaults: {
      target: [0, 0, 0],
      distance: 8.0,
      fov: 45,
    },
    wiggleBoneNames: ['Bone5', 'Bone6', 'Bone7', 'Bone8'],
    description: 'Raglan sleeve fleece crewneck sweatshirt with ribbed cuffs and hem.',
  },
  {
    id: 'sweatpants',
    name: 'Sweatpants',
    category: 'pants',
    modelFilename: 'Sweatpants.glb',
    modelPath: '/3d-assets/GLB/Sweatpants.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/sweatpants.jpg',
    garmentNodeName: 'Sweatpants',
    positionNodeName: 'ModelPosition_Sweatpants',
    masterClipName: 'WALK_Sweatpants',
    textures: {
      diffuse: '/3d-assets/sweatpants_diffuse.jpg',
      normal: '/3d-assets/sweatpants_normal.jpg',
      roughness: '/3d-assets/sweatpants_roughness.jpg',
    },
    regions: [
      {
        id: 'left-leg',
        name: 'Left Thigh',
        uvCenter: [0.31, 0.55],
        uvSpan: [0.20, 0.28],
        description: 'Upper wearer-left thigh print zone',
      },
      {
        id: 'right-leg',
        name: 'Right Thigh',
        uvCenter: [0.09, 0.55],
        uvSpan: [0.18, 0.28],
        description: 'Upper wearer-right thigh print zone',
      },
    ],
    cameraDefaults: {
      target: [0, -6.5, 0],
      distance: 12.0,
      fov: 45,
    },
    wiggleBoneNames: ['Bone1', 'Bone2', 'Bone3', 'Bone4', 'Bone5', 'Bone6', 'Bone7', 'Bone8'],
    description: 'Tapered fleece joggers with elasticized cuffs and drawstring waist.',
  },
  {
    id: 'jeans',
    name: 'Denim Jeans',
    category: 'pants',
    modelFilename: 'Jeans.glb',
    modelPath: '/3d-assets/GLB/Jeans.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/jeans.jpg',
    garmentNodeName: 'Jeans',
    positionNodeName: 'ModelPosition_jeans',
    masterClipName: 'WALK_jeans',
    textures: {
      diffuse: '/3d-assets/jeans_diffuse.jpg',
      normal: '/3d-assets/jeans_normal.jpg',
      roughness: '/3d-assets/jeans_roughness.jpg',
    },
    regions: [
      {
        id: 'front-leg',
        name: 'Front Leg',
        uvCenter: [0.34, 0.60],
        uvSpan: [0.20, 0.28],
        description: 'Front wearer-left upper leg panel',
      },
      {
        id: 'back-pocket',
        name: 'Back Pocket',
        uvCenter: [0.48, 0.14],
        uvSpan: [0.20, 0.20],
        description: 'Rear pocket and yoke',
      },
    ],
    cameraDefaults: {
      target: [0, -6.5, 0],
      distance: 12.0,
      fov: 45,
    },
    wiggleBoneNames: ['Bone1', 'Bone2', 'Bone3', 'Bone4', 'Bone5', 'Bone6', 'Bone7', 'Bone8'],
    description: 'Straight-leg denim trousers with authentic twill weave and rivet details.',
  },
  {
    id: 'tank-top',
    name: 'Tank Top',
    category: 't-shirts',
    modelFilename: 'tank-top.glb',
    modelPath: '/3d-assets/GLB/tank-top.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/tank-top.jpg',
    garmentNodeName: 'tank-top',
    positionNodeName: 'ModelPosition_tank-top',
    masterClipName: 'WALK_tank-top',
    textures: {
      diffuse: '/3d-assets/tank-top_diffuse.jpg',
      normal: '/3d-assets/tank-top_normal.jpg',
      roughness: '/3d-assets/tank-top_roughness.jpg',
    },
    regions: [
      {
        id: 'front',
        name: 'Front Chest',
        uvCenter: [0.26, 0.64],
        uvSpan: [0.28, 0.32],
        description: 'Deep scoop front placement',
      },
      {
        id: 'back',
        name: 'Racerback',
        uvCenter: [0.74, 0.65],
        uvSpan: [0.28, 0.32],
        description: 'Back spine panel',
      },
    ],
    cameraDefaults: {
      target: [0, 0, 0],
      distance: 7.5,
      fov: 45,
    },
    wiggleBoneNames: ['Bone1', 'Bone2', 'Bone3', 'Bone4', 'Bone5', 'Bone6', 'Bone7', 'Bone8'],
    description: 'Sleeveless ribbed cotton tank top with wide armholes.',
  },
  {
    id: 'cap',
    name: 'Baseball Cap',
    category: 'headwear',
    modelFilename: 'Cap.glb',
    modelPath: '/3d-assets/GLB/Cap.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/cap.jpg',
    garmentNodeName: 'Cap',
    positionNodeName: 'ModelPosition_Cap',
    masterClipName: 'WALK_Cap',
    textures: {
      diffuse: '/3d-assets/cap_diffuse.jpg',
      normal: '/3d-assets/cap_normal.jpg',
      roughness: '/3d-assets/cap_roughness.jpg',
    },
    regions: [
      {
        id: 'crown',
        name: 'Front Crown',
        uvCenter: [0.33, 0.75],
        uvSpan: [0.24, 0.24],
        description: 'Structured front panel above brim',
      },
      {
        id: 'back',
        name: 'Back Panels',
        uvCenter: [0.74, 0.79],
        uvSpan: [0.24, 0.24],
        description: 'Rear strap and crown panels',
      },
    ],
    cameraDefaults: {
      target: [0, 5.2, 0.3],
      distance: 4.2,
      fov: 40,
    },
    wiggleBoneNames: ['Bone1', 'Bone2', 'Bone3', 'Bone4', 'Bone5', 'Bone6', 'Bone7', 'Bone8'],
    description: 'Structured 6-panel cotton twill cap with curved visor.',
  },
  {
    id: 'balaclava',
    name: 'Balaclava',
    category: 'headwear',
    modelFilename: 'Balaclava.glb',
    modelPath: '/3d-assets/GLB/Balaclava.glb',
    thumbnailPath: '/3d-assets/GLB/Product_Images/balaclava.jpg',
    garmentNodeName: 'Balaclava',
    positionNodeName: 'ModelPosition_Balaclava',
    masterClipName: 'WALK_Balaclava',
    textures: {
      diffuse: '/3d-assets/balaclava_diffuse.jpg',
      normal: '/3d-assets/balaclava_normal.jpg',
      roughness: '/3d-assets/balaclava_roughness.jpg',
    },
    regions: [
      {
        id: 'forehead',
        name: 'Left Face / Crown',
        uvCenter: [0.20, 0.32],
        uvSpan: [0.24, 0.24],
        description: 'Wearer left face and crown panel',
      },
      {
        id: 'back',
        name: 'Right Face / Crown',
        uvCenter: [0.60, 0.32],
        uvSpan: [0.24, 0.24],
        description: 'Wearer right face and crown panel',
      },
    ],
    cameraDefaults: {
      target: [0, 4.2, 0.1],
      distance: 4.5,
      fov: 40,
    },
    wiggleBoneNames: ['Bone1', 'Bone2', 'Bone3', 'Bone4', 'Bone5', 'Bone6', 'Bone7', 'Bone8'],
    description: 'Form-fitting thermal knit balaclava with ergonomic eye portal.',
  },
];

export function getGarmentConfig(id: string): Garment3DConfig {
  const found = GARMENT_3D_CATALOG.find((g) => g.id === id);
  if (found) return found;
  return GARMENT_3D_CATALOG[0];
}
